'use strict';function z(h,a,b,e){h.M.me(h.kc,a,b,e,void 0)}function C(h,a,b){return h.M.Yf(h.kc,a,b,void 0,void 0)}function J(h,a,b,e){h.M.Qa?z(h,a,b,e):h.M.Aj()._OnMessageFromDOM({type:"event",component:h.kc,handler:a,dispatchOpts:e||null,data:b,responseId:null})}function L(h,a,b){h.M.S(h.kc,a,b)}function M(h,a){for(const [b,e]of a)L(h,b,e)}function N(h){h.Dd||(h.M.jj(h.bh),h.Dd=!0)}window.Sa=class{constructor(h,a){this.M=h;this.kc=a;this.Dd=!1;this.bh=()=>this.fa()}Jf(){}fa(){}};
function O(h){-1!==h.Vb&&(self.clearTimeout(h.Vb),h.Vb=-1)}window.Fi=class{constructor(h,a){this.Ve=h;this.zl=a;this.Vb=-1;this.Ed=-Infinity;this.dh=()=>{this.Vb=-1;this.Ed=Date.now();this.rc=!0;this.Ve();this.rc=!1};this.Cg=this.rc=!1}l(){O(this);this.dh=this.Ve=null}};"use strict";
function P(h,a){const b=a.elementId,e=h.ce(b,a);h.Ca.set(b,e);a.isVisible||(e.style.display="none");e.addEventListener("focus",()=>{Q(h,"elem-focused",b)});e.addEventListener("blur",()=>{Q(h,"elem-blurred",b)});h.td&&document.body.appendChild(e)}function R(h,a,b){L(h,a,e=>{const l=h.Ca.get(e.elementId);return b(l,e)})}function Q(h,a,b,e){e||(e={});e.elementId=b;z(h,a,e)}function S(h,a,b){var e;e||(e={});e.elementId=b;J(h,a,e)}
window.Qf=class extends self.Sa{constructor(h,a){super(h,a);this.Ca=new Map;this.td=!0;M(this,[["create",b=>P(this,b)],["destroy",b=>{{b=b.elementId;const e=this.Ca.get(b);this.td&&e.parentElement.removeChild(e);this.Ca.delete(b)}}],["set-visible",b=>{this.td&&(this.Ca.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.td){var e=this.Ca.get(b.elementId);e.style.left=b.left+"px";e.style.top=b.top+"px";e.style.width=b.width+"px";e.style.height=b.height+"px";b=b.fontSize;
null!==b&&(e.style.fontSize=b+"em")}}],["update-state",b=>{{const e=this.Ca.get(b.elementId);this.ec(e,b)}}],["focus",b=>this.Oe(b)],["set-css-style",b=>{this.Ca.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Ca.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Ca.get(b.elementId).removeAttribute(b.name)}]]);R(this,"get-element",b=>b)}ce(){throw Error("required override");}ec(){throw Error("required override");}Oe(h){var a=this.Ca.get(h.elementId);h.focus?
a.focus():a.blur()}};"use strict";
{const h=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(u){const g=document.createElement("script");g.async=!1;g.type="module";return u.Ml?new Promise(r=>{const v="c3_resolve_"+a;++a;self[v]=r;g.textContent=u.Ql+`\n\nself["${v}"]();`;document.head.appendChild(g)}):new Promise((r,v)=>{g.onload=r;g.onerror=v;g.src=u;document.head.appendChild(g)})}let e=!1,l=!1;function w(){if(!e){try{new Worker("blob://",{get type(){l=!0}})}catch(u){}e=!0}return l}const n=
/safari\//i.test(navigator.userAgent)&&!/chrome\/|chromium\/|edg\//i.test(navigator.userAgent);let f=new Audio;const m={"audio/webm; codecs=opus":!!f.canPlayType("audio/webm; codecs=opus")&&!n,"audio/ogg; codecs=opus":!!f.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!f.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!f.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!f.canPlayType("audio/mp4"),"audio/mpeg":!!f.canPlayType("audio/mpeg")};f=null;async function c(u){u=
await d(u);return(new TextDecoder("utf-8")).decode(u)}function d(u){return new Promise((g,r)=>{const v=new FileReader;v.onload=y=>g(y.target.result);v.onerror=y=>r(y);v.readAsArrayBuffer(u)})}const p=[];let t=0;window.RealFile=window.File;const x=[],B=new Map,F=new Map;let G=0;const I=[];self.runOnStartup=function(u){if("function"!==typeof u)throw Error("runOnStartup called without a function");I.push(u)};const k=new Set(["cordova","playable-ad","instant-games"]);let q=!1;window.ra=class u{constructor(g){this.Qa=
g.Sl;this.ib=null;this.X="";this.Rd=g.Pl;this.Uc={};this.Nb=this.Tc=null;this.zd=[];this.zc=this.da=this.Tb=null;this.Sb=-1;this.Fl=()=>this.nk();this.Rb=[];this.H=g.eh;this.uc="file"===location.protocol.substr(0,4);!this.Qa||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&w()||(this.Qa=!1);if("playable-ad"===this.H||"instant-games"===this.H)this.Qa=!1;if("cordova"===this.H&&this.Qa)if(/android/i.test(navigator.userAgent)){const r=/Chrome\/(\d+)/i.exec(navigator.userAgent);r&&90<=
parseInt(r[1],10)||(this.Qa=!1)}else this.Qa=!1;this.Jd=this.Wa=null;"html5"!==this.H&&"playable-ad"!==this.H||!this.uc||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.S("runtime","cordova-fetch-local-file",r=>this.Qj(r));this.S("runtime","create-job-worker",()=>this.Rj());"cordova"===this.H?document.addEventListener("deviceready",()=>this.mg(g)):this.mg(g)}l(){this.ze();this.ib&&
(this.ib=this.ib.onmessage=null);this.Tc&&(this.Tc.terminate(),this.Tc=null);this.Nb&&(this.Nb.l(),this.Nb=null);this.da&&(this.da.parentElement.removeChild(this.da),this.da=null)}ni(){return h&&"cordova"===this.H}le(){const g=navigator.userAgent;return h&&k.has(this.H)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(g)}async mg(g){"macos-wkwebview"===this.H&&this.Se({type:"ready"});if("playable-ad"===this.H){this.Wa=self.c3_base64files;this.Jd={};await this.oj();for(let v=0,y=g.Xb.length;v<
y;++v){var r=g.Xb[v].toLowerCase();this.Jd.hasOwnProperty(r)?g.Xb[v]={Ml:!0,Ql:this.Jd[r]}:this.Wa.hasOwnProperty(r)&&(g.Xb[v]=URL.createObjectURL(this.Wa[r]))}}g.Hl?this.X=g.Hl:(r=location.origin,this.X=("null"===r?"file:///":r)+location.pathname,r=this.X.lastIndexOf("/"),-1!==r&&(this.X=this.X.substr(0,r+1)));g.Ul&&(this.Uc=g.Ul);r=new MessageChannel;this.ib=r.port1;this.ib.onmessage=v=>this._OnMessageFromRuntime(v.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(v=>this.fk(v));
this.zc=new self.oi(this);await T(this.zc);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.Qa?await this.Gj(g,r.port2):await this.Fj(g,r.port2)}Ce(g){g=this.Uc.hasOwnProperty(g)?this.Uc[g]:g.endsWith("/workermain.js")&&this.Uc.hasOwnProperty("workermain.js")?this.Uc["workermain.js"]:"playable-ad"===this.H&&this.Wa.hasOwnProperty(g.toLowerCase())?this.Wa[g.toLowerCase()]:g;g instanceof Blob&&(g=URL.createObjectURL(g));
return g}async de(g,r,v){if(g.startsWith("blob:"))return new Worker(g,v);if("cordova"===this.H&&this.uc)return g=await this.Wc(v.Ll?g:this.Rd+g),new Worker(URL.createObjectURL(new Blob([g],{type:"application/javascript"})),v);g=new URL(g,r);if(location.origin!==g.origin){g=await fetch(g);if(!g.ok)throw Error("failed to fetch worker script");g=await g.blob();return new Worker(URL.createObjectURL(g),v)}return new Worker(g,v)}qb(){return Math.max(window.innerWidth,1)}pb(){return Math.max(window.innerHeight,
1)}lg(g){var r=this.zc;return{baseUrl:this.X,windowInnerWidth:this.qb(),windowInnerHeight:this.pb(),devicePixelRatio:window.devicePixelRatio,isFullscreen:u.ac(),projectData:g.$l,previewImageBlobs:window.cr_previewImageBlobs||this.Wa,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Yl||"",exportType:g.eh,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Zl,jobScheduler:{inputPort:r.gf,outputPort:r.vf,maxNumWorkers:r.Bl},
supportedAudioFormats:m,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Rd+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Rd+"opus.wasm.wasm",isFileProtocol:this.uc,isiOSCordova:this.ni(),isiOSWebView:this.le(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Gj(g,r){var v=this.Ce(g.Tl);this.Tc=await this.de(v,this.X,{type:"module",name:"Runtime",Ll:!0});this.da=document.createElement("canvas");this.da.style.display="none";v=this.da.transferControlToOffscreen();
document.body.appendChild(this.da);window.c3canvas=this.da;let y=g.Hf||[],E=g.Xb;y=await Promise.all(y.map(A=>this.Hb(A)));E=await Promise.all(E.map(A=>this.Hb(A)));if("cordova"===this.H)for(let A=0,D=g.$d.length;A<D;++A){const H=g.$d[A],K=H[0];if(K===g.Ef||"scriptsInEvents.js"===K||K.endsWith("/scriptsInEvents.js"))H[1]=await this.Hb(K)}this.Tc.postMessage(Object.assign(this.lg(g),{type:"init-runtime",isInWorker:!0,messagePort:r,canvas:v,workerDependencyScripts:y,engineScripts:E,projectScripts:g.$d,
mainProjectScript:g.Ef,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[r,v,...aa(this.zc)]);this.zd=x.map(A=>new A(this));this.kg();self.c3_callFunction=(A,D)=>this.Tb.Hj(A,D);"preview"===this.H&&(self.goToLastErrorScript=()=>this.me("runtime","go-to-last-error-script"))}async Fj(g,r){this.da=document.createElement("canvas");this.da.style.display="none";document.body.appendChild(this.da);window.c3canvas=this.da;this.zd=x.map(A=>new A(this));this.kg();var v=g.Xb.map(A=>"string"===typeof A?(new URL(A,
this.X)).toString():A);Array.isArray(g.Hf)&&v.unshift(...g.Hf);v=await Promise.all(v.map(A=>this.Hb(A)));await Promise.all(v.map(A=>b(A)));v=self.C3_ProjectScriptsStatus;const y=g.Ef,E=g.$d;for(let [A,D]of E)if(D||(D=A),A===y)try{D=await this.Hb(D),await b(D),"preview"!==this.H||v[A]||this.wg(A,"main script did not run to completion")}catch(H){this.wg(A,H)}else if("scriptsInEvents.js"===A||A.endsWith("/scriptsInEvents.js"))D=await this.Hb(D),await b(D);"preview"===this.H&&"object"!==typeof self.Vl.Wl?
(this.od(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(g=Object.assign(this.lg(g),{isInWorker:!1,messagePort:r,canvas:this.da,runOnStartupFunctions:I}),this.og(),this.Nb=self.C3_CreateRuntime(g),await self.C3_InitRuntime(this.Nb,g))}wg(g,r){this.od();console.error(`[Preview] Failed to load project main script (${g}): `,
r);alert(`Failed to load project main script (${g}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}og(){this.od()}od(){const g=window.Il;g&&(g.parentElement.removeChild(g),window.Il=null)}async Rj(){const g=await U(this.zc);return{outputPort:g,transferables:[g]}}Aj(){if(this.Qa)throw Error("not available in worker mode");return this.Nb}me(g,r,v,y,E){this.ib.postMessage({type:"event",component:g,handler:r,dispatchOpts:y||null,data:v,responseId:null},
E)}Yf(g,r,v,y,E){const A=G++,D=new Promise((H,K)=>{F.set(A,{resolve:H,reject:K})});this.ib.postMessage({type:"event",component:g,handler:r,dispatchOpts:y||null,data:v,responseId:A},E);return D}["_OnMessageFromRuntime"](g){const r=g.type;if("event"===r)return this.Wj(g);if("result"===r)this.rk(g);else if("runtime-ready"===r)this.sk();else if("alert-error"===r)this.od(),alert(g.message);else if("creating-runtime"===r)this.og();else throw Error(`unknown message '${r}'`);}Wj(g){const r=g.component,v=
g.handler,y=g.data,E=g.responseId;if(g=B.get(r))if(g=g.get(v)){var A=null;try{A=g(y)}catch(D){console.error(`Exception in '${r}' handler '${v}':`,D);null!==E&&this.nd(E,!1,""+D);return}if(null===E)return A;A&&A.then?A.then(D=>this.nd(E,!0,D)).catch(D=>{console.error(`Rejection from '${r}' handler '${v}':`,D);this.nd(E,!1,""+D)}):this.nd(E,!0,A)}else console.warn(`[DOM] No handler '${v}' for component '${r}'`);else console.warn(`[DOM] No event handlers for component '${r}'`)}nd(g,r,v){let y;v&&v.transferables&&
(y=v.transferables);this.ib.postMessage({type:"result",responseId:g,isOk:r,result:v},y)}rk(g){const r=g.responseId,v=g.isOk;g=g.result;const y=F.get(r);v?y.resolve(g):y.reject(g);F.delete(r)}S(g,r,v){let y=B.get(g);y||(y=new Map,B.set(g,y));if(y.has(r))throw Error(`[DOM] Component '${g}' already has handler '${r}'`);y.set(r,v)}static Fa(g){if(x.includes(g))throw Error("DOM handler already added");x.push(g)}kg(){for(const g of this.zd)if("runtime"===g.kc){this.Tb=g;return}throw Error("cannot find runtime DOM handler");
}fk(g){this.me("debugger","message",g)}sk(){for(const g of this.zd)g.Jf()}static ac(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||q)}static pd(g){q=!!g}jj(g){this.Rb.push(g);this.Re()}Uk(g){g=this.Rb.indexOf(g);if(-1===g)throw Error("invalid callback");this.Rb.splice(g,1);this.Rb.length||this.ze()}Re(){-1===this.Sb&&this.Rb.length&&(this.Sb=requestAnimationFrame(this.Fl))}ze(){-1!==this.Sb&&(cancelAnimationFrame(this.Sb),this.Sb=-1)}nk(){this.Sb=
-1;for(const g of this.Rb)g();this.Re()}ob(g){this.Tb.ob(g)}Gb(g){this.Tb.Gb(g)}Qe(){this.Tb.Qe()}gd(g){this.Tb.gd(g)}li(){return!!m["audio/webm; codecs=opus"]}async xl(g){g=await this.Yf("runtime","opus-decode",{arrayBuffer:g},null,[g]);return new Float32Array(g)}ki(g){return/^(?:[a-z\-]+:)?\/\//.test(g)||"data:"===g.substr(0,5)||"blob:"===g.substr(0,5)}Xf(g){return!this.ki(g)}async Hb(g){return"cordova"===this.H&&(g.startsWith("file:")||this.uc&&this.Xf(g))?(g.startsWith(this.X)&&(g=g.substr(this.X.length)),
g=await this.Wc(g),URL.createObjectURL(new Blob([g],{type:"application/javascript"}))):g}async Qj(g){const r=g.filename;switch(g.as){case "text":return await this.Lh(r);case "buffer":return await this.Wc(r);default:throw Error("unsupported type");}}Pf(g){const r=window.cordova.file.applicationDirectory+"www/"+g.toLowerCase();return new Promise((v,y)=>{window.resolveLocalFileSystemURL(r,E=>{E.file(v,y)},y)})}async Lh(g){g=await this.Pf(g);return await c(g)}Ae(){if(p.length&&!(8<=t)){t++;var g=p.shift();
this.pj(g.filename,g.Rl,g.Kl)}}Wc(g){return new Promise((r,v)=>{p.push({filename:g,Rl:y=>{t--;this.Ae();r(y)},Kl:y=>{t--;this.Ae();v(y)}});this.Ae()})}async pj(g,r,v){try{const y=await this.Pf(g),E=await d(y);r(E)}catch(y){v(y)}}Se(g){if("windows-webview2"===this.H)window.chrome.webview.postMessage(JSON.stringify(g));else if("macos-wkwebview"===this.H)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(g));else throw Error("cannot send wrapper message");}async oj(){const g=[];for(const [r,
v]of Object.entries(this.Wa))g.push(this.nj(r,v));await Promise.all(g)}async nj(g,r){if("object"===typeof r)this.Wa[g]=new Blob([r.str],{type:r.type}),this.Jd[g]=r.str;else{let v=await this.xj(r);v||(v=this.rj(r));this.Wa[g]=v}}async xj(g){try{return await (await fetch(g)).blob()}catch(r){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
r),null}}rj(g){g=this.Nk(g);return this.mj(g.data,g.Nl)}Nk(g){var r=g.indexOf(",");if(0>r)throw new URIError("expected comma in data: uri");var v=g.substring(r+1);r=g.substring(5,r).split(";");g=r[0]||"";const y=r[2];v="base64"===r[1]||"base64"===y?atob(v):decodeURIComponent(v);return{Nl:g,data:v}}mj(g,r){var v=g.length;let y=v>>2,E=new Uint8Array(v),A=new Uint32Array(E.buffer,0,y),D,H;for(H=D=0;D<y;++D)A[D]=g.charCodeAt(H++)|g.charCodeAt(H++)<<8|g.charCodeAt(H++)<<16|g.charCodeAt(H++)<<24;for(v&=
3;v--;)E[H]=g.charCodeAt(H),++H;return new Blob([E],{type:r})}}}"use strict";
{const h=self.ra;function a(k){return k.sourceCapabilities&&k.sourceCapabilities.firesTouchEvents||k.originalEvent&&k.originalEvent.sourceCapabilities&&k.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),e={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},l={dispatchUserScriptEvent:!0},w={dispatchRuntimeEvent:!0};function n(k){return new Promise((q,u)=>{const g=document.createElement("link");g.onload=()=>q(g);g.onerror=r=>u(r);g.rel=
"stylesheet";g.href=k;document.head.appendChild(g)})}function f(k){return new Promise((q,u)=>{const g=new Image;g.onload=()=>q(g);g.onerror=r=>u(r);g.src=k})}async function m(k){k=URL.createObjectURL(k);try{return await f(k)}finally{URL.revokeObjectURL(k)}}function c(k){return new Promise((q,u)=>{let g=new FileReader;g.onload=r=>q(r.target.result);g.onerror=r=>u(r);g.readAsText(k)})}async function d(k,q,u){if(!/firefox/i.test(navigator.userAgent))return await m(k);var g=await c(k);g=(new DOMParser).parseFromString(g,
"image/svg+xml");const r=g.documentElement;if(r.hasAttribute("width")&&r.hasAttribute("height")){const v=r.getAttribute("width"),y=r.getAttribute("height");if(!v.includes("%")&&!y.includes("%"))return await m(k)}r.setAttribute("width",q+"px");r.setAttribute("height",u+"px");g=(new XMLSerializer).serializeToString(g);k=new Blob([g],{type:"image/svg+xml"});return await m(k)}function p(k){do{if(k.parentNode&&k.hasAttribute("contenteditable"))return!0;k=k.parentNode}while(k);return!1}const t=new Set(["input",
"textarea","datalist","select"]),x=new Set(["canvas","body","html"]);function B(k){x.has(k.target.tagName.toLowerCase())&&k.preventDefault()}function F(k){(k.metaKey||k.ctrlKey)&&k.preventDefault()}self.C3_GetSvgImageSize=async function(k){k=await m(k);if(0<k.width&&0<k.height)return[k.width,k.height];{k.style.position="absolute";k.style.left="0px";k.style.top="0px";k.style.visibility="hidden";document.body.appendChild(k);const q=k.getBoundingClientRect();document.body.removeChild(k);return[q.width,
q.height]}};self.C3_RasterSvgImageBlob=async function(k,q,u,g,r){k=await d(k,q,u);const v=document.createElement("canvas");v.width=g;v.height=r;v.getContext("2d").drawImage(k,0,0,q,u);return v};let G=!1;document.addEventListener("pause",()=>G=!0);document.addEventListener("resume",()=>G=!1);function I(){try{return window.parent&&window.parent.document.hasFocus()}catch(k){return!1}}h.Fa(class extends self.Sa{constructor(k){super(k,"runtime");this.Jg=!0;this.Ub=-1;this.Bf="any";this.xg=this.yg=!1;this.mf=
this.Lc=this.xb=null;k.S("canvas","update-size",g=>this.Kk(g));k.S("runtime","invoke-download",g=>this.ck(g));k.S("runtime","raster-svg-image",g=>this.pk(g));k.S("runtime","get-svg-image-size",g=>this.Zj(g));k.S("runtime","set-target-orientation",g=>this.uk(g));k.S("runtime","register-sw",()=>this.qk());k.S("runtime","post-to-debugger",g=>this.sg(g));k.S("runtime","go-to-script",g=>this.sg(g));k.S("runtime","before-start-ticking",()=>this.Nj());k.S("runtime","debug-highlight",g=>this.Sj(g));k.S("runtime",
"enable-device-orientation",()=>this.lj());k.S("runtime","enable-device-motion",()=>this.kj());k.S("runtime","add-stylesheet",g=>this.Lj(g));k.S("runtime","alert",g=>this.He(g));k.S("runtime","hide-cordova-splash",()=>this.$j());const q=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",g=>{const r=g.target;q.has(r.tagName.toLowerCase())||p(r)||g.preventDefault()});const u=k.da;window.addEventListener("selectstart",B);window.addEventListener("gesturehold",B);u.addEventListener("selectstart",
B);u.addEventListener("gesturehold",B);window.addEventListener("touchstart",B,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",B,{passive:!1}),u.addEventListener("pointerdown",B)):u.addEventListener("touchstart",B);this.Ec=0;window.addEventListener("mousedown",g=>{1===g.button&&g.preventDefault()});window.addEventListener("mousewheel",F,{passive:!1});window.addEventListener("wheel",F,{passive:!1});window.addEventListener("resize",()=>this.Lk());window.addEventListener("fullscreenchange",
()=>this.fc());window.addEventListener("webkitfullscreenchange",()=>this.fc());window.addEventListener("mozfullscreenchange",()=>this.fc());window.addEventListener("fullscreenerror",g=>this.Ke(g));window.addEventListener("webkitfullscreenerror",g=>this.Ke(g));window.addEventListener("mozfullscreenerror",g=>this.Ke(g));k.le()&&window.addEventListener("focusout",()=>{{const v=document.activeElement;if(v){var g=v.tagName.toLowerCase();var r=new Set("email number password search tel text url".split(" "));
g="textarea"===g?!0:"input"===g?r.has(v.type.toLowerCase()||"text"):p(v)}else g=!1}g||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=g=>this.Mk(g);this.Ob=new Set;this.Kd=new WeakSet;this.hb=!1}Nj(){"cordova"===this.M.H?(document.addEventListener("pause",()=>this.Pe(!0)),document.addEventListener("resume",()=>this.Pe(!1))):document.addEventListener("visibilitychange",()=>this.Pe(document.hidden));return{isSuspended:!(!document.hidden&&!G)}}Jf(){window.addEventListener("focus",()=>
this.ic("window-focus"));window.addEventListener("blur",()=>{this.ic("window-blur",{parentHasFocus:I()});this.Ec=0});window.addEventListener("focusin",q=>{q=q.target;(t.has(q.tagName.toLowerCase())||p(q))&&this.ic("keyboard-blur")});window.addEventListener("keydown",q=>this.pg("keydown",q));window.addEventListener("keyup",q=>this.pg("keyup",q));window.addEventListener("dblclick",q=>this.Me("dblclick",q,e));window.addEventListener("wheel",q=>this.hk(q));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
q=>{this.De(q);this.hc("pointerdown",q)}),this.M.Qa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.Lc=new self.Fi(()=>this.vj(),5),this.Lc.Cg=!0,window.addEventListener("pointerrawupdate",q=>this.lk(q))):window.addEventListener("pointermove",q=>this.hc("pointermove",q)),window.addEventListener("pointerup",q=>this.hc("pointerup",q)),window.addEventListener("pointercancel",q=>this.hc("pointercancel",q))):(window.addEventListener("mousedown",q=>{this.De(q);this.Ne("pointerdown",
q)}),window.addEventListener("mousemove",q=>this.Ne("pointermove",q)),window.addEventListener("mouseup",q=>this.Ne("pointerup",q)),window.addEventListener("touchstart",q=>{this.De(q);this.md("pointerdown",q)}),window.addEventListener("touchmove",q=>this.md("pointermove",q)),window.addEventListener("touchend",q=>this.md("pointerup",q)),window.addEventListener("touchcancel",q=>this.md("pointercancel",q)));const k=()=>this.Qe();window.addEventListener("pointerup",k,!0);window.addEventListener("touchend",
k,!0);window.addEventListener("click",k,!0);window.addEventListener("keydown",k,!0);window.addEventListener("gamepadconnected",k,!0)}ic(k,q){z(this,k,q||null,w)}qb(){return this.M.qb()}pb(){return this.M.pb()}Lk(){const k=this.qb(),q=this.pb();this.ic("window-resize",{innerWidth:k,innerHeight:q,devicePixelRatio:window.devicePixelRatio,isFullscreen:h.ac()});this.M.le()&&(-1!==this.Ub&&clearTimeout(this.Ub),this.tg(k,q,0))}Vk(k,q,u){-1!==this.Ub&&clearTimeout(this.Ub);this.Ub=setTimeout(()=>this.tg(k,
q,u),48)}tg(k,q,u){const g=this.qb(),r=this.pb();this.Ub=-1;g!=k||r!=q?this.ic("window-resize",{innerWidth:g,innerHeight:r,devicePixelRatio:window.devicePixelRatio,isFullscreen:h.ac()}):10>u&&this.Vk(g,r,u+1)}uk(k){this.Bf=k.targetOrientation}tl(){const k=this.Bf;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(k).catch(q=>console.warn("[Construct 3] Failed to lock orientation: ",q));else try{let q=!1;screen.lockOrientation?q=screen.lockOrientation(k):screen.webkitLockOrientation?
q=screen.webkitLockOrientation(k):screen.mozLockOrientation?q=screen.mozLockOrientation(k):screen.msLockOrientation&&(q=screen.msLockOrientation(k));q||console.warn("[Construct 3] Failed to lock orientation")}catch(q){console.warn("[Construct 3] Failed to lock orientation: ",q)}}fc(){const k=h.ac();k&&"any"!==this.Bf&&this.tl();z(this,"fullscreenchange",{isFullscreen:k,innerWidth:this.qb(),innerHeight:this.pb()})}Ke(k){console.warn("[Construct 3] Fullscreen request failed: ",k);z(this,"fullscreenerror",
{isFullscreen:h.ac(),innerWidth:this.qb(),innerHeight:this.pb()})}Pe(k){k?this.M.ze():this.M.Re();z(this,"visibilitychange",{hidden:k})}pg(k,q){"Backspace"===q.key&&B(q);const u=b.get(q.code)||q.code;J(this,k,{code:u,key:q.key,which:q.which,repeat:q.repeat,altKey:q.altKey,ctrlKey:q.ctrlKey,metaKey:q.metaKey,shiftKey:q.shiftKey,timeStamp:q.timeStamp},e)}hk(k){z(this,"wheel",{clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,deltaX:k.deltaX,deltaY:k.deltaY,deltaZ:k.deltaZ,deltaMode:k.deltaMode,
timeStamp:k.timeStamp},e)}Me(k,q,u){a(q)||J(this,k,{button:q.button,buttons:q.buttons,clientX:q.clientX,clientY:q.clientY,pageX:q.pageX,pageY:q.pageY,timeStamp:q.timeStamp},u)}Ne(k,q){if(!a(q)){var u=this.Ec;"pointerdown"===k&&0!==u?k="pointermove":"pointerup"===k&&0!==q.buttons&&(k="pointermove");J(this,k,{pointerId:1,pointerType:"mouse",button:q.button,buttons:q.buttons,lastButtons:u,clientX:q.clientX,clientY:q.clientY,pageX:q.pageX,pageY:q.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:q.timeStamp},e);this.Ec=q.buttons;this.Me(q.type,q,l)}}hc(k,q){if(this.Lc&&"pointermove"!==k){var u=this.Lc;u.rc||(O(u),u.Ed=Date.now())}u=0;"mouse"===q.pointerType&&(u=this.Ec);J(this,k,{pointerId:q.pointerId,pointerType:q.pointerType,button:q.button,buttons:q.buttons,lastButtons:u,clientX:q.clientX,clientY:q.clientY,pageX:q.pageX,pageY:q.pageY,width:q.width||0,height:q.height||0,pressure:q.pressure||0,tangentialPressure:q.tangentialPressure||0,tiltX:q.tiltX||0,
tiltY:q.tiltY||0,twist:q.twist||0,timeStamp:q.timeStamp},e);"mouse"===q.pointerType&&(u="mousemove","pointerdown"===k?u="mousedown":"pointerup"===k&&(u="mouseup"),this.Me(u,q,l),this.Ec=q.buttons)}lk(k){this.mf=k;k=this.Lc;if(-1===k.Vb){var q=Date.now(),u=q-k.Ed,g=k.zl;u>=g&&k.Cg?(k.Ed=q,k.rc=!0,k.Ve(),k.rc=!1):k.Vb=self.setTimeout(k.dh,Math.max(g-u,4))}}vj(){this.hc("pointermove",this.mf);this.mf=null}md(k,q){for(let u=0,g=q.changedTouches.length;u<g;++u){const r=q.changedTouches[u];J(this,k,{pointerId:r.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:r.clientX,clientY:r.clientY,pageX:r.pageX,pageY:r.pageY,width:2*(r.radiusX||r.webkitRadiusX||0),height:2*(r.radiusY||r.webkitRadiusY||0),pressure:r.force||r.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:r.rotationAngle||0,timeStamp:q.timeStamp},e)}}De(k){window!==window.top&&window.focus();this.ng(k.target)&&document.activeElement&&!this.ng(document.activeElement)&&document.activeElement.blur()}ng(k){return!k||k===document||
k===window||k===document.body||"canvas"===k.tagName.toLowerCase()}lj(){this.yg||(this.yg=!0,window.addEventListener("deviceorientation",k=>this.Uj(k)),window.addEventListener("deviceorientationabsolute",k=>this.Vj(k)))}kj(){this.xg||(this.xg=!0,window.addEventListener("devicemotion",k=>this.Tj(k)))}Uj(k){z(this,"deviceorientation",{absolute:!!k.absolute,alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0,timeStamp:k.timeStamp,webkitCompassHeading:k.webkitCompassHeading,webkitCompassAccuracy:k.webkitCompassAccuracy},
e)}Vj(k){z(this,"deviceorientationabsolute",{absolute:!!k.absolute,alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0,timeStamp:k.timeStamp},e)}Tj(k){let q=null;var u=k.acceleration;u&&(q={x:u.x||0,y:u.y||0,z:u.z||0});u=null;var g=k.accelerationIncludingGravity;g&&(u={x:g.x||0,y:g.y||0,z:g.z||0});g=null;const r=k.rotationRate;r&&(g={alpha:r.alpha||0,beta:r.beta||0,gamma:r.gamma||0});z(this,"devicemotion",{acceleration:q,accelerationIncludingGravity:u,rotationRate:g,interval:k.interval,timeStamp:k.timeStamp},
e)}Kk(k){const q=this.M.da;q.style.width=k.styleWidth+"px";q.style.height=k.styleHeight+"px";q.style.marginLeft=k.marginLeft+"px";q.style.marginTop=k.marginTop+"px";this.Jg&&(q.style.display="",this.Jg=!1)}ck(k){const q=k.url;k=k.filename;const u=document.createElement("a"),g=document.body;u.textContent=k;u.href=q;u.download=k;g.appendChild(u);u.click();g.removeChild(u)}async pk(k){var q=k.imageBitmapOpts;k=await self.C3_RasterSvgImageBlob(k.blob,k.imageWidth,k.imageHeight,k.surfaceWidth,k.surfaceHeight);
q=q?await createImageBitmap(k,q):await createImageBitmap(k);return{imageBitmap:q,transferables:[q]}}async Zj(k){return await self.C3_GetSvgImageSize(k.blob)}async Lj(k){await n(k.url)}Qe(){var k=[...this.Ob];this.Ob.clear();if(!this.hb)for(const q of k)(k=q.play())&&k.catch(()=>{this.Kd.has(q)||this.Ob.add(q)})}ob(k){if("function"!==typeof k.play)throw Error("missing play function");this.Kd.delete(k);let q;try{q=k.play()}catch(u){this.Ob.add(k);return}q&&q.catch(()=>{this.Kd.has(k)||this.Ob.add(k)})}Gb(k){this.Ob.delete(k);
this.Kd.add(k)}gd(k){this.hb=!!k}$j(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Sj(k){if(k.show){this.xb||(this.xb=document.createElement("div"),this.xb.id="inspectOutline",document.body.appendChild(this.xb));var q=this.xb;q.style.display="";q.style.left=k.left-1+"px";q.style.top=k.top-1+"px";q.style.width=k.width+2+"px";q.style.height=k.height+2+"px";q.textContent=k.name}else this.xb&&(this.xb.style.display="none")}qk(){window.C3_RegisterSW&&window.C3_RegisterSW()}sg(k){window.c3_postToMessagePort&&
(k.from="runtime",window.c3_postToMessagePort(k))}Hj(k,q){return C(this,"js-invoke-function",{name:k,params:q})}He(k){alert(k.message)}Mk(k){"entered-fullscreen"===k?(h.pd(!0),this.fc()):"exited-fullscreen"===k?(h.pd(!1),this.fc()):console.warn("Unknown wrapper message: ",k)}})}"use strict";
async function T(h){if(h.yl)throw Error("already initialised");h.yl=!0;var a=h.Qd.Ce("dispatchworker.js");h.Ye=await h.Qd.de(a,h.X,{name:"DispatchWorker"});a=new MessageChannel;h.gf=a.port1;h.Ye.postMessage({type:"_init","in-port":a.port2},[a.port2]);h.vf=await U(h)}function aa(h){return[h.gf,h.vf]}
async function U(h){const a=h.Lg.length;var b=h.Qd.Ce("jobworker.js");b=await h.Qd.de(b,h.X,{name:"JobWorker"+a});const e=new MessageChannel,l=new MessageChannel;h.Ye.postMessage({type:"_addJobWorker",port:e.port1},[e.port1]);b.postMessage({type:"init",number:a,"dispatch-port":e.port2,"output-port":l.port2},[e.port2,l.port2]);h.Lg.push(b);return l.port1}
self.oi=class{constructor(h){this.Qd=h;this.X=h.X;this.X="preview"===h.H?this.X+"workers/":this.X+h.Rd;this.Bl=Math.min(navigator.hardwareConcurrency||2,16);this.Ye=null;this.Lg=[];this.vf=this.gf=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ra({Sl:!1,Tl:"workermain.js",Xb:["scripts/c3runtime.js"],$d:[],Ef:"",Pl:"scripts/",Hf:[],eh:"html5"}));"use strict";
{const h=180/Math.PI;self.Ra=class extends self.Sa{constructor(a){super(a,"audio");this.yd=this.o=null;this.Cd=this.df=!1;this.lb=()=>this.ul();this.La=[];this.W=[];this.Va=null;this.Ng="";this.Qg=-1;this.Kc=new Map;this.qf=1;this.hb=!1;this.Cf=0;this.Td=1;this.af=0;this.Ug="HRTF";this.Fg="inverse";this.Wg=600;this.Tg=1E4;this.Yg=1;this.Hg=this.wf=!1;this.ah=this.M.li();this.Ma=new Map;this.Jb=new Set;this.hf=!1;this.rf="";this.Ab=null;self.C3Audio_OnMicrophoneStream=(b,e)=>this.gk(b,e);this.xd=null;
self.C3Audio_GetOutputStream=()=>this.Xj();self.C3Audio_DOMInterface=this;M(this,[["create-audio-context",b=>this.qj(b)],["play",b=>this.Ok(b)],["stop",b=>this.rl(b)],["stop-all",()=>this.sl()],["set-paused",b=>this.kl(b)],["set-volume",b=>this.pl(b)],["fade-volume",b=>this.wj(b)],["set-master-volume",b=>this.il(b)],["set-muted",b=>this.jl(b)],["set-silent",b=>this.ml(b)],["set-looping",b=>this.hl(b)],["set-playback-rate",b=>this.ll(b)],["seek",b=>this.Wk(b)],["preload",b=>this.Pk(b)],["unload",b=>
this.vl(b)],["unload-all",()=>this.wl()],["set-suspended",b=>this.nl(b)],["add-effect",b=>this.gg(b)],["set-effect-param",b=>this.bl(b)],["remove-effects",b=>this.Rk(b)],["tick",b=>this.Jk(b)],["load-state",b=>this.dk(b)]])}async qj(a){a.isiOSCordova&&(this.wf=!0);this.Cf=a.timeScaleMode;this.Ug=["equalpower","HRTF","soundfield"][a.panningModel];this.Fg=["linear","inverse","exponential"][a.distanceModel];this.Wg=a.refDistance;this.Tg=a.maxDistance;this.Yg=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.ah||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.o=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.o=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.hg();this.o.onstatechange=()=>{"running"!==this.o.state&&this.hg()};this.yd=this.o.createGain();this.yd.connect(this.o.destination);b=a.listenerPos;this.o.listener.setPosition(b[0],b[1],b[2]);this.o.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.ee();try{await Promise.all(a.preloadList.map(e=>this.kd(e.originalUrl,e.url,e.type,!1)))}catch(e){console.error("[Construct 3] Preloading sounds failed: ",e)}return{sampleRate:this.o.sampleRate}}hg(){this.Cd||(this.df=!1,window.addEventListener("pointerup",this.lb,!0),window.addEventListener("touchend",this.lb,!0),window.addEventListener("click",this.lb,!0),window.addEventListener("keydown",this.lb,!0),this.Cd=!0)}sj(){this.Cd&&(this.df=!0,window.removeEventListener("pointerup",this.lb,!0),window.removeEventListener("touchend",
this.lb,!0),window.removeEventListener("click",this.lb,!0),window.removeEventListener("keydown",this.lb,!0),this.Cd=!1)}ul(){if(!this.df){var a=this.o;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),e=a.createBufferSource();e.buffer=b;e.connect(a.destination);e.start(0);"running"===a.state&&this.sj()}}wa(){return this.o}ee(){return this.o.currentTime}mb(){return this.yd}Tf(a){return(a=this.Ma.get(a.toLowerCase()))?a[0].la():this.mb()}nh(a,b){a=a.toLowerCase();let e=this.Ma.get(a);
e||(e=[],this.Ma.set(a,e));b.el(e.length);b.ol(a);e.push(b);this.vg(a)}vg(a){let b=this.mb();const e=this.Ma.get(a);if(e&&e.length){b=e[0].la();for(let l=0,w=e.length;l<w;++l){const n=e[l];l+1===w?n.pa(this.mb()):n.pa(e[l+1].la())}}for(const l of this.bb(a))l.Gi(b);this.Ab&&this.rf===a&&(this.Ab.disconnect(),this.Ab.connect(b))}Yc(){return this.qf}cd(){return this.hb}cl(){this.Hg=!0}Nh(a,b){return b?this.M.xl(a).then(e=>{const l=this.o.createBuffer(1,e.length,48E3);l.getChannelData(0).set(e);return l}):
new Promise((e,l)=>{this.o.decodeAudioData(a,e,l)})}ob(a){this.M.ob(a)}Gb(a){this.M.Gb(a)}Zf(a){let b=0;for(let e=0,l=this.W.length;e<l;++e){const w=this.W[e];this.W[b]=w;w.ha===a?w.l():++b}this.W.length=b}Hi(){let a=0;for(let b=0,e=this.La.length;b<e;++b){const l=this.La[b];this.La[a]=l;l.nb()?l.l():++a}this.La.length=a}*bb(a){if(a)for(const b of this.W)self.Ra.Oh(b.aa,a)&&(yield b);else this.Va&&!this.Va.qa()&&(yield this.Va)}async kd(a,b,e,l,w){for(const n of this.La)if(n.Zb()===b)return await V(n),
n;if(w)return null;l&&(this.wf||this.Hg)&&this.Hi();w="audio/webm; codecs=opus"===e&&!this.ah;l&&w&&this.cl();a=!l||this.wf||w?new self.Ih(this,a,b,e,l,w):new self.Dh(this,a,b,e,l);this.La.push(a);await V(a);return a}async Be(a,b,e,l,w){for(const n of this.W)if(n.Zb()===b&&(n.be()||w))return n.Ri(l),n;a=await this.kd(a,b,e,w);l="html5"===a.Te?new self.Eh(a.A,a,l):new self.Jh(a.A,a,l);this.W.push(l);return l}ij(a){let b=this.Kc.get(a);if(!b){let e=null;b={Gf:0,Ol:new Promise(l=>e=l),resolve:e};this.Kc.set(a,
b)}b.Gf++}Tk(a){const b=this.Kc.get(a);if(!b)throw Error("expected pending tag");b.Gf--;0===b.Gf&&(b.resolve(),this.Kc.delete(a))}we(a){a||(a=this.Ng);return(a=this.Kc.get(a))?a.Ol:Promise.resolve()}ld(){if(0<this.Jb.size)N(this);else for(const a of this.W)if(a.Vf()){N(this);break}}fa(){for(var a of this.Jb)a.fa();a=this.ee();for(var b of this.W)b.fa(a);b=this.W.filter(e=>e.Vf()).map(e=>e.Yb());z(this,"state",{tickCount:this.Qg,audioInstances:b,analysers:[...this.Jb].map(e=>e.Wh())});0===b.length&&
0===this.Jb.size&&this.Dd&&(this.M.Uk(this.bh),this.Dd=!1)}ne(a,b,e){z(this,"trigger",{type:a,tag:b,aiid:e})}async Ok(a){const b=a.originalUrl,e=a.url,l=a.type,w=a.isMusic,n=a.tag,f=a.isLooping,m=a.vol,c=a.pos,d=a.panning;let p=a.off;0<p&&!a.trueClock&&(this.o.getOutputTimestamp?(a=this.o.getOutputTimestamp(),p=p-a.performanceTime/1E3+a.contextTime):p=p-performance.now()/1E3+this.o.currentTime);this.Ng=n;this.ij(n);try{this.Va=await this.Be(b,e,l,n,w),d?(this.Va.fd(!0),this.Va.Pi(d.x,d.y,d.angle,
d.innerAngle,d.outerAngle,d.outerGain),d.hasOwnProperty("uid")&&this.Va.Si(d.uid)):this.Va.fd(!1),this.Va.Play(f,m,c,p)}catch(t){console.error("[Construct 3] Audio: error starting playback: ",t);return}finally{this.Tk(n)}N(this)}rl(a){a=a.tag;for(const b of this.bb(a))b.gb()}sl(){for(const a of this.W)a.gb()}kl(a){const b=a.tag;a=a.paused;for(const e of this.bb(b))a?e.cc():e.ed();this.ld()}pl(a){const b=a.tag;a=a.vol;for(const e of this.bb(b))e.hd(a)}async wj(a){const b=a.tag,e=a.vol,l=a.duration;
a=a.stopOnEnd;await this.we(b);for(const w of this.bb(b))w.Ph(e,l,a);this.ld()}il(a){this.qf=a.vol;for(const b of this.W)b.rd()}jl(a){const b=a.tag;a=a.isMuted;for(const e of this.bb(b))e.bg(a)}ml(a){this.hb=a.isSilent;this.M.gd(this.hb);for(const b of this.W)b.qd()}hl(a){const b=a.tag;a=a.isLooping;for(const e of this.bb(b))e.te(a)}async ll(a){const b=a.tag;a=a.rate;await this.we(b);for(const e of this.bb(b))e.dg(a)}async Wk(a){const b=a.tag;a=a.pos;await this.we(b);for(const e of this.bb(b))e.re(a)}async Pk(a){const b=
a.originalUrl,e=a.url,l=a.type;a=a.isMusic;try{await this.Be(b,e,l,"",a)}catch(w){console.error("[Construct 3] Audio: error preloading: ",w)}}async vl(a){if(a=await this.kd("",a.url,a.type,a.isMusic,!0))a.l(),a=this.La.indexOf(a),-1!==a&&this.La.splice(a,1)}wl(){for(const a of this.La)a.l();this.La.length=0}nl(a){a=a.isSuspended;!a&&this.o.resume&&this.o.resume();for(const b of this.W)b.ue(a);a&&this.o.suspend&&this.o.suspend()}Jk(a){this.Td=a.timeScale;this.af=a.gameTime;this.Qg=a.tickCount;if(0!==
this.Cf)for(var b of this.W)b.Ib();(b=a.listenerPos)&&this.o.listener.setPosition(b[0],b[1],b[2]);for(const e of a.instPans){a=e.uid;for(const l of this.W)l.Ua===a&&l.cg(e.x,e.y,e.angle)}}async gg(a){var b=a.type;const e=a.tag;var l=a.params;if("filter"===b)l=new self.xh(this,...l);else if("delay"===b)l=new self.vh(this,...l);else if("convolution"===b){b=null;try{b=await this.kd(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(w){console.log("[Construct 3] Audio: error loading convolution: ",
w);return}l=new self.uh(this,b.Ka,...l);l.$k(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)l=new self.yh(this,...l);else if("phaser"===b)l=new self.Ah(this,...l);else if("gain"===b)l=new self.zh(this,...l);else if("tremolo"===b)l=new self.Ch(this,...l);else if("ringmod"===b)l=new self.Bh(this,...l);else if("distortion"===b)l=new self.wh(this,...l);else if("compressor"===b)l=new self.th(this,...l);else if("analyser"===b)l=new self.sh(this,...l);else throw Error("invalid effect type");this.nh(e,
l);this.ug()}bl(a){const b=a.index,e=a.param,l=a.value,w=a.ramp,n=a.time;a=this.Ma.get(a.tag);!a||0>b||b>=a.length||(a[b].za(e,l,w,n),this.ug())}Rk(a){a=a.tag.toLowerCase();const b=this.Ma.get(a);if(b&&b.length){for(const e of b)e.l();this.Ma.delete(a);this.vg(a)}}ej(a){this.Jb.add(a);this.ld()}Qk(a){this.Jb.delete(a)}ug(){this.hf||(this.hf=!0,Promise.resolve().then(()=>this.uj()))}uj(){const a={};for(const [b,e]of this.Ma)a[b]=e.map(l=>l.Yb());z(this,"fxstate",{fxstate:a});this.hf=!1}async dk(a){const b=
a.saveLoadMode;if(3!==b)for(var e of this.W)e.nb()&&1===b||(e.nb()||2!==b)&&e.gb();for(const l of this.Ma.values())for(const w of l)w.l();this.Ma.clear();this.Td=a.timeScale;this.af=a.gameTime;e=a.listenerPos;this.o.listener.setPosition(e[0],e[1],e[2]);this.hb=a.isSilent;this.M.gd(this.hb);this.qf=a.masterVolume;e=[];for(const l of Object.values(a.effects))e.push(Promise.all(l.map(w=>this.gg(w))));await Promise.all(e);await Promise.all(a.playing.map(l=>this.Ij(l,b)));this.ld()}async Ij(a,b){if(3!==
b){var e=a.bufferOriginalUrl,l=a.bufferUrl,w=a.bufferType,n=a.isMusic,f=a.tag,m=a.isLooping,c=a.volume,d=a.playbackTime;if(!n||1!==b)if(n||2!==b){b=null;try{b=await this.Be(e,l,w,f,n)}catch(p){console.error("[Construct 3] Audio: error loading audio state: ",p);return}b.si(a.pan);b.Play(m,c,d,0);a.isPlaying||b.cc();b.Fe(a)}}}gk(a,b){this.Ab&&this.Ab.disconnect();this.rf=b.toLowerCase();this.Ab=this.o.createMediaStreamSource(a);this.Ab.connect(this.Tf(this.rf))}Xj(){this.xd||(this.xd=this.o.createMediaStreamDestination(),
this.yd.connect(this.xd));return this.xd.stream}static Oh(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static dj(a){return a*h}static Mh(a){return Math.pow(10,a/20)}static Rf(a){return Math.max(Math.min(self.Ra.Mh(a),1),0)}static ri(a){return Math.log(a)/Math.log(10)*20}static pi(a){return self.Ra.ri(Math.max(Math.min(a,1),0))}static Jl(a,b){return 1-Math.exp(-b*a)}};self.ra.Fa(self.Ra)}"use strict";function V(h){h.Id||(h.Id=h.Ee());return h.Id}
self.Kf=class{constructor(h,a,b,e,l){this.A=h;this.El=a;this.Db=b;this.oa=e;this.Al=l;this.Te="";this.Id=null}l(){this.Id=this.A=null}Ee(){}wa(){return this.A.wa()}ge(){return this.El}Zb(){return this.Db}fe(){return this.oa}nb(){return this.Al}Ta(){}};"use strict";
self.Dh=class extends self.Kf{constructor(h,a,b,e,l){super(h,a,b,e,l);this.Te="html5";this.ca=new Audio;this.ca.crossOrigin="anonymous";this.ca.autoplay=!1;this.ca.preload="auto";this.Ac=this.Bc=null;this.ca.addEventListener("canplaythrough",()=>!0);this.Ic=this.wa().createGain();this.Dc=null;this.ca.addEventListener("canplay",()=>{this.Bc&&(this.Bc(),this.Ac=this.Bc=null);!this.Dc&&this.ca&&(this.Dc=this.wa().createMediaElementSource(this.ca),this.Dc.connect(this.Ic))});this.onended=null;this.ca.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.ca.addEventListener("error",w=>{console.error(`[Construct 3] Audio '${this.Db}' error: `,w);this.Ac&&(this.Ac(w),this.Ac=this.Bc=null)})}l(){this.A.Zf(this);this.Ic.disconnect();this.Ic=null;this.Dc.disconnect();this.Dc=null;this.ca&&!this.ca.paused&&this.ca.pause();this.ca=this.onended=null;super.l()}Ee(){return new Promise((h,a)=>{this.Bc=h;this.Ac=a;this.ca.src=this.Db})}ka(){return this.ca}Ta(){return this.ca.duration}};"use strict";
async function ba(h){if(h.tb)return h.tb;var a=h.A.M;if("cordova"===a.H&&a.Xf(h.Db)&&a.uc)h.tb=await a.Wc(h.Db);else{a=await fetch(h.Db);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);h.tb=await a.arrayBuffer()}}async function ca(h){if(h.Ka)return h.Ka;h.Ka=await h.A.Nh(h.tb,h.Cl);h.tb=null}
self.Ih=class extends self.Kf{constructor(h,a,b,e,l,w){super(h,a,b,e,l);this.Te="webaudio";this.Ka=this.tb=null;this.Cl=!!w}l(){this.A.Zf(this);this.Ka=this.tb=null;super.l()}async Ee(){try{await ba(this),await ca(this)}catch(h){console.error(`[Construct 3] Failed to load audio '${this.Db}': `,h)}}Ta(){return this.Ka?this.Ka.duration:0}};"use strict";
{let h=0;self.Lf=class{constructor(a,b,e){this.A=a;this.ha=b;this.aa=e;this.sd=h++;this.ia=this.wa().createGain();this.ia.connect(this.mb());this.O=null;this.wc=!1;this.Ya=[0,0,0];this.Xa=[0,0,0];this.Z=!0;this.ta=this.$a=this.Y=!1;this.Rc=1;this.Mb=!1;this.jb=1;a=this.A.Cf;this.kf=1===a&&!this.nb()||2===a;this.oc=this.Ua=-1;this.$g=!1}l(){this.ha=this.A=null;this.O&&(this.O.disconnect(),this.O=null);this.ia.disconnect();this.ia=null}wa(){return this.A.wa()}mb(){return this.A.Tf(this.aa)}Yc(){return this.A.Yc()}Xc(){return this.kf?
this.A.af:performance.now()/1E3}ge(){return this.ha.ge()}Zb(){return this.ha.Zb()}fe(){return this.ha.fe()}nb(){return this.ha.nb()}Ri(a){this.aa=a}qa(){}be(){}IsPlaying(){return!this.Z&&!this.Y&&!this.qa()}Vf(){return!this.Z&&!this.qa()}Eb(){}Ta(){return this.ha.Ta()}Play(){}gb(){}cc(){}ed(){}hd(a){this.Rc=a;this.ia.gain.cancelScheduledValues(0);this.oc=-1;this.ia.gain.value=this.he()}Ph(a,b,e){if(!this.Mb){a*=this.Yc();var l=this.ia.gain;l.cancelScheduledValues(0);var w=this.A.ee();b=w+b;l.setValueAtTime(l.value,
w);l.linearRampToValueAtTime(a,b);this.Rc=a;this.oc=b;this.$g=e}}rd(){this.hd(this.Rc)}fa(a){-1!==this.oc&&a>=this.oc&&(this.oc=-1,this.$g&&this.gb(),this.A.ne("fade-ended",this.aa,this.sd))}he(){const a=this.Rc*this.Yc();return isFinite(a)?a:0}bg(a){a=!!a;this.Mb!==a&&(this.Mb=a,this.qd())}cd(){return this.A.cd()}qd(){}te(){}dg(a){this.jb!==a&&(this.jb=a,this.Ib())}Ib(){}re(){}ue(){}fd(a){a=!!a;this.wc!==a&&((this.wc=a)?(this.O||(this.O=this.wa().createPanner(),this.O.panningModel=this.A.Ug,this.O.distanceModel=
this.A.Fg,this.O.refDistance=this.A.Wg,this.O.maxDistance=this.A.Tg,this.O.rolloffFactor=this.A.Yg),this.ia.disconnect(),this.ia.connect(this.O),this.O.connect(this.mb())):(this.O.disconnect(),this.ia.disconnect(),this.ia.connect(this.mb())))}Pi(a,b,e,l,w,n){this.wc&&(this.cg(a,b,e),a=self.Ra.dj,this.O.coneInnerAngle=a(l),this.O.coneOuterAngle=a(w),this.O.coneOuterGain=n)}cg(a,b,e){this.wc&&(this.Ya[0]=a,this.Ya[1]=b,this.Ya[2]=0,this.Xa[0]=Math.cos(e),this.Xa[1]=Math.sin(e),this.Xa[2]=0,this.O.setPosition(...this.Ya),
this.O.setOrientation(...this.Xa))}Si(a){this.Ua=a}ie(){}Gi(a){const b=this.O||this.ia;b.disconnect();b.connect(a)}Yb(){return{aiid:this.sd,tag:this.aa,duration:this.Ta(),volume:this.Rc,isPlaying:this.IsPlaying(),playbackTime:this.Eb(),playbackRate:this.jb,uid:this.Ua,bufferOriginalUrl:this.ge(),bufferUrl:"",bufferType:this.fe(),isMusic:this.nb(),isLooping:this.ta,isMuted:this.Mb,resumePosition:this.ie(),pan:this.di()}}Fe(a){this.dg(a.playbackRate);this.bg(a.isMuted)}di(){if(!this.O)return null;const a=
this.O;return{pos:this.Ya,orient:this.Xa,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.Ua}}si(a){if(a){this.fd(!0);a=this.O;var b=a.pos;this.Ya[0]=b[0];this.Ya[1]=b[1];this.Ya[2]=b[2];b=a.orient;this.Xa[0]=b[0];this.Xa[1]=b[1];this.Xa[2]=b[2];a.setPosition(...this.Ya);a.setOrientation(...this.Xa);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.Ua=a.uid}else this.fd(!1)}}}"use strict";
self.Eh=class extends self.Lf{constructor(h,a,b){super(h,a,b);this.ha.Ic.connect(this.ia);this.ha.onended=()=>this.Je()}l(){this.gb();this.ha.Ic.disconnect();super.l()}ka(){return this.ha.ka()}Je(){this.Z=!0;this.Ua=-1;this.A.ne("ended",this.aa,this.sd)}qa(){return this.ka().ended}be(){return this.Z?!0:this.qa()}Eb(){let h=this.ka().currentTime;this.ta||(h=Math.min(h,this.Ta()));return h}Play(h,a,b){const e=this.ka();1!==e.playbackRate&&(e.playbackRate=1);e.loop!==h&&(e.loop=h);this.hd(a);e.muted&&
(e.muted=!1);if(e.currentTime!==b)try{e.currentTime=b}catch(l){console.warn(`[Construct 3] Exception seeking audio '${this.ha.Zb()}' to position '${b}': `,l)}this.A.ob(e);this.Y=this.Z=!1;this.ta=h;this.jb=1}gb(){const h=this.ka();h.paused||h.pause();this.A.Gb(h);this.Z=!0;this.Y=!1;this.Ua=-1}cc(){if(!(this.Y||this.Z||this.qa())){var h=this.ka();h.paused||h.pause();this.A.Gb(h);this.Y=!0}}ed(){!this.Y||this.Z||this.qa()||(this.A.ob(this.ka()),this.Y=!1)}qd(){this.ka().muted=this.Mb||this.cd()}te(h){h=
!!h;this.ta!==h&&(this.ta=h,this.ka().loop=h)}Ib(){let h=this.jb;this.kf&&(h*=this.A.Td);try{this.ka().playbackRate=h}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${h}':`,a)}}re(h){if(!this.Z&&!this.qa())try{this.ka().currentTime=h}catch(a){console.warn(`[Construct 3] Error seeking audio to '${h}': `,a)}}ie(){return this.Eb()}ue(h){h?this.IsPlaying()?(this.ka().pause(),this.$a=!0):this.$a=!1:this.$a&&(this.A.ob(this.ka()),this.$a=!1)}};"use strict";
function W(h){h.B&&h.B.disconnect();h.B=null;h.jc=null}
self.Jh=class extends self.Lf{constructor(h,a,b){super(h,a,b);this.B=null;this.Ld=e=>this.Je(e);this.cf=!0;this.jc=null;this.ja=this.Md=this.Nd=0;this.sf=1}l(){this.gb();W(this);this.Ld=null;super.l()}Je(h){this.Y||this.$a||h.target!==this.jc||(this.Z=this.cf=!0,this.Ua=-1,W(this),this.A.ne("ended",this.aa,this.sd))}qa(){return!this.Z&&this.B&&this.B.loop||this.Y?!1:this.cf}be(){return!this.B||this.Z?!0:this.qa()}Eb(){let h;h=this.Y?this.ja:this.Md+(this.Xc()-this.Nd)*this.jb;this.ta||(h=Math.min(h,
this.Ta()));return h}Play(h,a,b,e){this.sf=1;this.hd(a);W(this);this.B=this.wa().createBufferSource();this.B.buffer=this.ha.Ka;this.B.connect(this.ia);this.jc=this.B;this.B.onended=this.Ld;this.B.loop=h;this.B.start(e,b);this.Y=this.Z=this.cf=!1;this.ta=h;this.jb=1;this.Nd=this.Xc();this.Md=b}gb(){if(this.B)try{this.B.stop(0)}catch(h){}this.Z=!0;this.Y=!1;this.Ua=-1}cc(){this.Y||this.Z||this.qa()||(this.ja=this.Eb(),this.ta&&(this.ja%=this.Ta()),this.Y=!0,this.B.stop(0))}ed(){!this.Y||this.Z||this.qa()||
(W(this),this.B=this.wa().createBufferSource(),this.B.buffer=this.ha.Ka,this.B.connect(this.ia),this.jc=this.B,this.B.onended=this.Ld,this.B.loop=this.ta,this.rd(),this.Ib(),this.B.start(0,this.ja),this.Nd=this.Xc(),this.Md=this.ja,this.Y=!1)}he(){return super.he()*this.sf}qd(){this.sf=this.Mb||this.cd()?0:1;this.rd()}te(h){h=!!h;this.ta!==h&&(this.ta=h,this.B&&(this.B.loop=h))}Ib(){let h=this.jb;this.kf&&(h*=this.A.Td);this.B&&(this.B.playbackRate.value=h)}re(h){this.Z||this.qa()||(this.Y?this.ja=
h:(this.cc(),this.ja=h,this.ed()))}ie(){return this.ja}ue(h){h?this.IsPlaying()?(this.$a=!0,this.ja=this.Eb(),this.ta&&(this.ja%=this.Ta()),this.B.stop(0)):this.$a=!1:this.$a&&(W(this),this.B=this.wa().createBufferSource(),this.B.buffer=this.ha.Ka,this.B.connect(this.ia),this.jc=this.B,this.B.onended=this.Ld,this.B.loop=this.ta,this.rd(),this.Ib(),this.B.start(0,this.ja),this.Nd=this.Xc(),this.Md=this.ja,this.$a=!1)}Fe(h){super.Fe(h);this.ja=h.resumePosition}};"use strict";
{class h{constructor(a){this.A=a;this.o=a.wa();this.sc=-1;this.oa=this.aa="";this.s=null}l(){this.o=null}el(a){this.sc=a}ol(a){this.aa=a}G(){return this.o.createGain()}la(){}pa(){}F(a,b,e,l){a.cancelScheduledValues(0);if(0===l)a.value=b;else{var w=this.o.currentTime;l+=w;switch(e){case 0:a.setValueAtTime(b,l);break;case 1:a.setValueAtTime(a.value,w);a.linearRampToValueAtTime(b,l);break;case 2:a.setValueAtTime(a.value,w),a.exponentialRampToValueAtTime(b,l)}}}Yb(){return{type:this.oa,tag:this.aa,params:this.s}}}
self.xh=class extends h{constructor(a,b,e,l,w,n,f){super(a);this.oa="filter";this.s=[b,e,l,w,n,f];this.D=this.G();this.h=this.G();this.h.gain.value=f;this.g=this.G();this.g.gain.value=1-f;this.L=this.o.createBiquadFilter();this.L.type=b;this.L.frequency.value=e;this.L.detune.value=l;this.L.Q.value=w;this.L.gain.vlaue=n;this.D.connect(this.L);this.D.connect(this.g);this.L.connect(this.h)}l(){this.D.disconnect();this.L.disconnect();this.h.disconnect();this.g.disconnect();super.l()}pa(a){this.h.disconnect();
this.h.connect(a);this.g.disconnect();this.g.connect(a)}la(){return this.D}za(a,b,e,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[5]=b;this.F(this.h.gain,b,e,l);this.F(this.g.gain,1-b,e,l);break;case 1:this.s[1]=b;this.F(this.L.frequency,b,e,l);break;case 2:this.s[2]=b;this.F(this.L.detune,b,e,l);break;case 3:this.s[3]=b;this.F(this.L.Q,b,e,l);break;case 4:this.s[4]=b,this.F(this.L.gain,b,e,l)}}};self.vh=class extends h{constructor(a,b,e,l){super(a);this.oa="delay";this.s=[b,e,l];this.D=
this.G();this.h=this.G();this.h.gain.value=l;this.g=this.G();this.g.gain.value=1-l;this.Cc=this.G();this.sa=this.o.createDelay(b);this.sa.delayTime.value=b;this.nc=this.G();this.nc.gain.value=e;this.D.connect(this.Cc);this.D.connect(this.g);this.Cc.connect(this.h);this.Cc.connect(this.sa);this.sa.connect(this.nc);this.nc.connect(this.Cc)}l(){this.D.disconnect();this.h.disconnect();this.g.disconnect();this.Cc.disconnect();this.sa.disconnect();this.nc.disconnect();super.l()}pa(a){this.h.disconnect();
this.h.connect(a);this.g.disconnect();this.g.connect(a)}la(){return this.D}za(a,b,e,l){const w=self.Ra.Rf;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[2]=b;this.F(this.h.gain,b,e,l);this.F(this.g.gain,1-b,e,l);break;case 4:this.s[1]=w(b);this.F(this.nc.gain,w(b),e,l);break;case 5:this.s[0]=b,this.F(this.sa.delayTime,b,e,l)}}};self.uh=class extends h{constructor(a,b,e,l){super(a);this.oa="convolution";this.s=[e,l];this.Bg=this.Ag="";this.D=this.G();this.h=this.G();this.h.gain.value=l;this.g=
this.G();this.g.gain.value=1-l;this.lc=this.o.createConvolver();this.lc.normalize=e;this.lc.buffer=b;this.D.connect(this.lc);this.D.connect(this.g);this.lc.connect(this.h)}l(){this.D.disconnect();this.lc.disconnect();this.h.disconnect();this.g.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}la(){return this.D}za(a,b,e,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.s[1]=b,this.F(this.h.gain,b,e,l),this.F(this.g.gain,1-b,e,l)}}$k(a,
b){this.Ag=a;this.Bg=b}Yb(){const a=super.Yb();a.bufferOriginalUrl=this.Ag;a.bufferUrl="";a.bufferType=this.Bg;return a}};self.yh=class extends h{constructor(a,b,e,l,w,n){super(a);this.oa="flanger";this.s=[b,e,l,w,n];this.D=this.G();this.g=this.G();this.g.gain.value=1-n/2;this.h=this.G();this.h.gain.value=n/2;this.pc=this.G();this.pc.gain.value=w;this.sa=this.o.createDelay(b+e);this.sa.delayTime.value=b;this.J=this.o.createOscillator();this.J.frequency.value=l;this.$=this.G();this.$.gain.value=e;
this.D.connect(this.sa);this.D.connect(this.g);this.sa.connect(this.h);this.sa.connect(this.pc);this.pc.connect(this.sa);this.J.connect(this.$);this.$.connect(this.sa.delayTime);this.J.start(0)}l(){this.J.stop(0);this.D.disconnect();this.sa.disconnect();this.J.disconnect();this.$.disconnect();this.g.disconnect();this.h.disconnect();this.pc.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}la(){return this.D}za(a,b,e,l){switch(a){case 0:b=Math.max(Math.min(b/
100,1),0);this.s[4]=b;this.F(this.h.gain,b/2,e,l);this.F(this.g.gain,1-b/2,e,l);break;case 6:this.s[1]=b/1E3;this.F(this.$.gain,b/1E3,e,l);break;case 7:this.s[2]=b;this.F(this.J.frequency,b,e,l);break;case 8:this.s[3]=b/100,this.F(this.pc.gain,b/100,e,l)}}};self.Ah=class extends h{constructor(a,b,e,l,w,n,f){super(a);this.oa="phaser";this.s=[b,e,l,w,n,f];this.D=this.G();this.g=this.G();this.g.gain.value=1-f/2;this.h=this.G();this.h.gain.value=f/2;this.L=this.o.createBiquadFilter();this.L.type="allpass";
this.L.frequency.value=b;this.L.detune.value=e;this.L.Q.value=l;this.J=this.o.createOscillator();this.J.frequency.value=n;this.$=this.G();this.$.gain.value=w;this.D.connect(this.L);this.D.connect(this.g);this.L.connect(this.h);this.J.connect(this.$);this.$.connect(this.L.frequency);this.J.start(0)}l(){this.J.stop(0);this.D.disconnect();this.L.disconnect();this.J.disconnect();this.$.disconnect();this.g.disconnect();this.h.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();
this.g.connect(a)}la(){return this.D}za(a,b,e,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[5]=b;this.F(this.h.gain,b/2,e,l);this.F(this.g.gain,1-b/2,e,l);break;case 1:this.s[0]=b;this.F(this.L.frequency,b,e,l);break;case 2:this.s[1]=b;this.F(this.L.detune,b,e,l);break;case 3:this.s[2]=b;this.F(this.L.Q,b,e,l);break;case 6:this.s[3]=b;this.F(this.$.gain,b,e,l);break;case 7:this.s[4]=b,this.F(this.J.frequency,b,e,l)}}};self.zh=class extends h{constructor(a,b){super(a);this.oa="gain";this.s=
[b];this.v=this.G();this.v.gain.value=b}l(){this.v.disconnect();super.l()}pa(a){this.v.disconnect();this.v.connect(a)}la(){return this.v}za(a,b,e,l){const w=self.Ra.Rf;switch(a){case 4:this.s[0]=w(b),this.F(this.v.gain,w(b),e,l)}}};self.Ch=class extends h{constructor(a,b,e){super(a);this.oa="tremolo";this.s=[b,e];this.v=this.G();this.v.gain.value=1-e/2;this.J=this.o.createOscillator();this.J.frequency.value=b;this.$=this.G();this.$.gain.value=e/2;this.J.connect(this.$);this.$.connect(this.v.gain);
this.J.start(0)}l(){this.J.stop(0);this.J.disconnect();this.$.disconnect();this.v.disconnect();super.l()}pa(a){this.v.disconnect();this.v.connect(a)}la(){return this.v}za(a,b,e,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.s[1]=b;this.F(this.v.gain,1-b/2,e,l);this.F(this.$.gain,b/2,e,l);break;case 7:this.s[0]=b,this.F(this.J.frequency,b,e,l)}}};self.Bh=class extends h{constructor(a,b,e){super(a);this.oa="ringmod";this.s=[b,e];this.D=this.G();this.h=this.G();this.h.gain.value=e;this.g=this.G();
this.g.gain.value=1-e;this.Oc=this.G();this.Oc.gain.value=0;this.J=this.o.createOscillator();this.J.frequency.value=b;this.J.connect(this.Oc.gain);this.J.start(0);this.D.connect(this.Oc);this.D.connect(this.g);this.Oc.connect(this.h)}l(){this.J.stop(0);this.J.disconnect();this.Oc.disconnect();this.D.disconnect();this.h.disconnect();this.g.disconnect();super.l()}pa(a){this.h.disconnect();this.h.connect(a);this.g.disconnect();this.g.connect(a)}la(){return this.D}za(a,b,e,l){switch(a){case 0:b=Math.max(Math.min(b/
100,1),0);this.s[1]=b;this.F(this.h.gain,b,e,l);this.F(this.g.gain,1-b,e,l);break;case 7:this.s[0]=b,this.F(this.J.frequency,b,e,l)}}};self.wh=class extends h{constructor(a,b,e,l,w,n){super(a);this.oa="distortion";this.s=[b,e,l,w,n];this.D=this.G();this.Pd=this.G();this.Od=this.G();this.al(l,w);this.h=this.G();this.h.gain.value=n;this.g=this.G();this.g.gain.value=1-n;this.Xd=this.o.createWaveShaper();this.We=new Float32Array(65536);this.yj(b,e);this.Xd.curve=this.We;this.D.connect(this.Pd);this.D.connect(this.g);
this.Pd.connect(this.Xd);this.Xd.connect(this.Od);this.Od.connect(this.h)}l(){this.D.disconnect();this.Pd.disconnect();this.Xd.disconnect();this.Od.disconnect();this.h.disconnect();this.g.disconnect();super.l()}al(a,b){.01>a&&(a=.01);this.Pd.gain.value=a;this.Od.gain.value=Math.pow(1/a,.6)*b}yj(a,b){for(let e=0;32768>e;++e){let l=e/32768;l=this.ql(l,a,b);this.We[32768+e]=l;this.We[32768-e-1]=-l}}ql(a,b,e){e=1.05*e*b-b;const l=0>a?-a:a;return(l<b?l:b+e*self.Ra.Jl(l-b,1/e))*(0>a?-1:1)}pa(a){this.h.disconnect();
this.h.connect(a);this.g.disconnect();this.g.connect(a)}la(){return this.D}za(a,b,e,l){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.s[4]=b,this.F(this.h.gain,b,e,l),this.F(this.g.gain,1-b,e,l)}}};self.th=class extends h{constructor(a,b,e,l,w,n){super(a);this.oa="compressor";this.s=[b,e,l,w,n];this.v=this.o.createDynamicsCompressor();this.v.threshold.value=b;this.v.knee.value=e;this.v.ratio.value=l;this.v.attack.value=w;this.v.release.value=n}l(){this.v.disconnect();super.l()}pa(a){this.v.disconnect();
this.v.connect(a)}la(){return this.v}za(){}};self.sh=class extends h{constructor(a,b,e){super(a);this.oa="analyser";this.s=[b,e];this.v=this.o.createAnalyser();this.v.fftSize=b;this.v.smoothingTimeConstant=e;this.Gg=new Float32Array(this.v.frequencyBinCount);this.Zg=new Uint8Array(b);this.Xg=this.Qb=0;this.A.ej(this)}l(){this.A.Qk(this);this.v.disconnect();super.l()}fa(){this.v.getFloatFrequencyData(this.Gg);this.v.getByteTimeDomainData(this.Zg);const a=this.v.fftSize;let b=this.Qb=0;for(var e=0;e<
a;++e){let l=(this.Zg[e]-128)/128;0>l&&(l=-l);this.Qb<l&&(this.Qb=l);b+=l*l}e=self.Ra.pi;this.Qb=e(this.Qb);this.Xg=e(Math.sqrt(b/a))}pa(a){this.v.disconnect();this.v.connect(a)}la(){return this.v}za(){}Wh(){return{tag:this.aa,index:this.sc,peak:this.Qb,rms:this.Xg,binCount:this.v.frequencyBinCount,freqBins:this.Gg}}}}"use strict";
async function da(h){var a=X(h.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:h.duration,startDelay:0,weakMagnitude:h.weakMag,strongMagnitude:h.strongMag})}catch(b){console.warn("[Gamepad] Failed to vibrate gamepad: ",b)}}function Y(){return Array.from(navigator.getGamepads()).filter(h=>h&&h.connected)}function X(h){for(const a of Y())if(a.index===h)return a;return null}
self.ra.Fa(class extends self.Sa{constructor(h){super(h,"gamepad");this.Kg=!!navigator.getGamepads;this.jf=!1;L(this,"is-supported",()=>this.Kg);L(this,"ready",()=>{this.jf=!0;for(const a of Y())z(this,"gamepad-connected",{index:a.index,id:a.id});this.Kg&&N(this)});L(this,"vibrate",a=>da(a));L(this,"reset-vibrate",a=>{(a=X(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});window.addEventListener("gamepadconnected",a=>{this.jf&&(a=a.gamepad,z(this,"gamepad-connected",{index:a.index,id:a.id}))});
window.addEventListener("gamepaddisconnected",a=>{this.jf&&z(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of Y()){const b=a.vibrationActuator;b&&b.reset&&b.reset()}})}fa(){var h=Y();h.length&&(h=h.map(a=>({index:a.index,id:a.id,buttons:a.buttons.map(b=>({pressed:b.pressed,value:b.value})),axes:a.axes})),z(this,"input-update",h))}});"use strict";
async function ea(h,a){a=a.type;let b=!0;0===a?b=await fa():1===a&&(b=await ha());z(h,"permission-result",{type:a,result:b})}async function fa(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(h){return console.warn("[Touch] Failed to request orientation permission: ",h),!1}}
async function ha(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(h){return console.warn("[Touch] Failed to request motion permission: ",h),!1}}self.ra.Fa(class extends self.Sa{constructor(h){super(h,"touch");L(this,"request-permission",a=>ea(this,a))}});"use strict";
self.ra.Fa(class extends self.Sa{constructor(h){super(h,"mouse");L(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";function ia(h){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>z(h,"sw-message",a.data))}
function ja(h){h=h.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(h).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(h):screen.webkitLockOrientation?a=screen.webkitLockOrientation(h):screen.mozLockOrientation?a=screen.mozLockOrientation(h):screen.msLockOrientation&&(a=screen.msLockOrientation(h));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.ra.Fa(class extends self.Sa{constructor(h){super(h,"browser");this.H="";M(this,[["get-initial-state",a=>this.Le(a)],["ready-for-sw-messages",()=>ia(this)],["alert",a=>this.He(a)],["close",()=>this.Ie()],["set-focus",a=>this.Oe(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ja(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const e=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===
a||"windows-webview2"===a?window.open(b,"_blank"):this.Xl||(2===e?window.top.location=b:1===e?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.H||"macos-wkwebview"===this.H)self.ra.pd(!0),this.M.Se({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":
2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.H||"macos-wkwebview"===this.H?(self.ra.pd(!1),this.M.Se({type:"set-fullscreen",fullscreen:!1})):
document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{z(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{z(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{z(this,"hashchange",{location:location.toString()})});
document.addEventListener("backbutton",()=>{z(this,"backbutton")})}Le(h){this.H=h.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}He(h){alert(h.message)}Ie(){navigator.app&&navigator.app.exitApp?navigator.app.exitApp():
navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}Oe(h){h=h.isFocus;if("nwjs"===this.H){const a="nwjs"===this.H?nw.Window.get():null;h?a.focus():a.blur()}else h?window.focus():window.blur()}});"use strict";
async function ka(h){if(!h.Bb)try{h.Bb=await navigator.wakeLock.request("screen"),h.Bb.addEventListener("release",()=>{console.log("[Construct 3] Screen wake lock released");h.Bb=null;z(h,"wake-lock-released")}),console.log("[Construct 3] Screen wake lock acquired"),z(h,"wake-lock-acquired")}catch(a){console.warn("[Construct 3] Failed to acquire screen wake lock: ",a),z(h,"wake-lock-error")}}
function Z(){var h=document.body;const a=h.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");h=getComputedStyle(h);h=[h.getPropertyValue("--temp-sai-top"),h.getPropertyValue("--temp-sai-right"),h.getPropertyValue("--temp-sai-bottom"),h.getPropertyValue("--temp-sai-left")].map(b=>{b=parseInt(b,10);
return isFinite(b)?b:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return h}
self.ra.Fa(class extends self.Sa{constructor(h){super(h,"platform-info");M(this,[["get-initial-state",()=>this.Le()],["request-wake-lock",()=>ka(this)],["release-wake-lock",()=>{this.Bb&&(this.Bb.release(),this.Bb=null)}]]);window.addEventListener("resize",()=>{z(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:Z()})});this.Bb=null}Le(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:Z(),supportsWakeLock:!!navigator.wakeLock}}});"use strict";
{const h=[],a=2*Math.PI;function b(f){f%=a;0>f&&(f+=a);return f}class e{constructor(f,m,c,d,p,t){this.sc=f;this.tc=m;this.kb=c;this.aa=d;this.Wd=p;this.Dg=t}Fb(){return{tag:this.aa,interp:this.tc,userData:this.Wd,cvt:this.Dg}}eb(){return this.tc}ii(){return"undefined"!==typeof this.Wd}Nf(f){switch(this.kb){case 0:return f;case 1:return Math.fround(f);case 2:return 2===this.tc&&(f=b(f),f/=Math.PI,f=32767*(f-1)),f|=0,-32768>f?-32768:32767<f?32767:f;case 3:return 2===this.tc&&(f=b(f),f/=a,f*=255),f|=
0,0>f?0:255<f?255:f;default:return f}}fg(f,m,c){switch(this.kb){case 0:f.setFloat64(m,c);m+=8;break;case 1:f.setFloat32(m,c);m+=4;break;case 2:f.setInt16(m,c);m+=2;break;case 3:f.setUint8(m,c);m+=1;break;default:f.setFloat32(m,c),m+=4}return m}dd(f){if(2!==this.tc)return f;2===this.kb?f=(f/32767+1)*Math.PI:3===this.kb&&(f=f/255*a);return f}static ad(f,m,c,d,p){switch(f){case 0:return p?c:m;case 1:return m+d*(c-m);case 2:return m===c?f=0:(f=Math.sin(m)*Math.sin(c)+Math.cos(m)*Math.cos(c),f=1<=f?0:
-1>=f?Math.PI:Math.acos(f)),m=0>=Math.cos(c)*Math.sin(m)-Math.sin(c)*Math.cos(m)?b(m+f*d):b(m-f*d);default:return p?c:m}}}class l{constructor(f,m){this.timestamp=f;this.data=m}}class w{constructor(f,m,c){this.va=f;this.b=f.b;this.I=m;this.U=c;this.mc=[];this.mc.length=this.va.ya.length;this.pf=this.Fd=0;this.Ig=this.Ud=!1;this.ba=[];this.N=this.C=this.Ea=null}Fb(){var f=[];for(let c=0,d=this.va.ya.length;c<d;++c)f.push(this.eb(this.va.Sd,c));f={id:this.I,nid:this.U,isTimedOut:this.mi(),interpValues:f,
latestUpdate:null};const m=this.Zh();m&&(f.latestUpdate={timestamp:m.timestamp,data:m.data});return f}$f(f){this.Ig=!!f}xe(f,m){f=f.netValues;var c=this.va.ya;const d=c.length;this.Ud=!1;for(let p=0;p<d;++p){const t=c[p].Nf(f[p]);this.mc[p]!==t&&(this.mc[p]=t,this.Fd=m,this.va.Mi(m))}f=m-this.Fd;m-=this.pf;c=this.va.zg;(this.Ud=100>f&&0===c?!0:1E3>f&&1>=c?95<=m:495<=m)&&this.va.ji()}ye(f,m,c){const d=this.va.ya;this.pf=c;f.setUint16(m,this.U);m+=2;for(let p=0,t=this.mc.length;p<t;++p)m=d[p].fg(f,
m,this.mc[p]);return m}ae(f,m){for(let c=0,d=this.ba.length;c<d;++c){const p=this.ba[c];if(p.timestamp===f)return;if(p.timestamp>f){this.ba.splice(c,0,new l(f,m));return}}this.ba.push(new l(f,m))}mi(){return 0===this.ba.length?!1:this.ba[this.ba.length-1].timestamp<this.va.Sd-3E3}fa(){for(;2<this.ba.length&&this.ba[0]!==this.Ea&&this.ba[0]!==this.C&&this.ba[0]!==this.N;)this.ba.shift();const f=this.va.Sd;if(!(this.N&&this.N.timestamp>f&&this.C&&this.C.timestamp<f)){this.N=null;for(let m=0,c=this.ba.length;m<
c;++m){const d=this.ba[m];if(d.timestamp<=f){if(!this.C||d.timestamp>this.C.timestamp)this.Ea=this.C,this.C=d}else{this.N=d;break}}}}Zh(){return 0===this.ba.length?null:this.ba[this.ba.length-1]}eb(f,m){if(!this.N&&!this.C)return 0;if(this.N&&!this.C)return this.N.data[m];const c=this.va.ya;let d,p,t;if(!this.N&&this.C){if(this.Ea){var x=this.Ea.timestamp;d=this.Ea.data[m];p=this.C.timestamp;t=this.C.data[m];f>this.C.timestamp+this.va.Bd&&(f=this.C.timestamp+this.va.Bd);x=x===p?0:(f-x)/(p-x);return e.ad(c[m].eb(),
d,t,x,!0)}return this.C.data[m]}x=this.C.timestamp;d=this.C.data[m];p=this.N.timestamp;t=this.N.data[m];x=x===p?0:(f-x)/(p-x);return e.ad(c[m].eb(),d,t,x,!1)}}class n{constructor(f,m,c,d){this.b=f;this.Pc=m;this.Qc=c;this.U=this.b.ci();this.zg=d;this.Wd={};this.Na=0;this.Bd=250;switch(this.zg){case 1:this.Bd=500;break;case 2:this.Bd=2500}this.ya=[];this.Da=[];this.yb=new Map;this.Wb=new Set;this.Hc=this.pf=this.Fd=this.Fc=0;this.Lb=!1;this.wd=[];this.Gc=new Map;this.Sd=0;this.b.ph(this)}sb(f){this.U=
f}Mi(f){this.Fd=f}ji(){this.Hc++}dl(){this.Lb=!0}cb(f,m,c,d,p){f=new e(this.ya.length,f,m,c,d,p);switch(m){case 0:this.Na+=8;break;case 1:this.Na+=4;break;case 2:this.Na+=2;break;case 3:this.Na+=1}this.ya.push(f)}ae(f,m,c){this.ai(m).ae(f,c)}fa(){this.Sd=this.b.$c();for(const f of this.Da)f.fa()}bi(){const f=[];for(const m of this.ya){const c={tag:m.aa,precision:m.kb,interp:m.eb(),clientvaluetag:m.Dg};m.ii()&&(c.userdata=m.Wd);f.push(c)}return f}Oi(f){this.Na=this.ya.length=0;for(const m of f)this.cb(m.interp,
m.precision,m.tag,m.userdata,m.clientvaluetag)}ai(f){let m=this.Gc.get(f);if(m)return m;m=new w(this,-1,f);this.Gc.set(f,m);this.Da.push(m);return m}$h(f){let m=this.yb.get(f);if(m)return m;m=new w(this,f,this.rh());this.yb.set(f,m);this.Da.push(m);return m}rh(){do this.Fc++,65535<this.Fc&&(this.Fc=0);while(this.Wb.has(this.Fc));const f=this.Fc;this.Wb.add(f);return f}oe(f){const m=f.I,c=f.U;this.b.j()&&!this.Lb&&this.wd.push(c);this.yb.delete(m);this.Gc.delete(c);this.Wb.delete(c);f=this.Da.indexOf(f);
-1<f&&this.Da.splice(f,1)}Kh(){this.wd.length=0;this.yb.clear();this.Gc.clear();this.Wb.clear();this.Da.length=0}xe(f,m){this.Hc=0;for(var c of this.Da)c.$f(!1);for(let d=0,p=f.length;d<p;++d){c=f[d];const t=this.$h(c.uid);t.$f(!0);t.xe(c,m)}for(const d of this.Da)d.Ig||h.push(d);for(const d of h)this.oe(d);h.length=0}ye(f,m,c){f.setUint16(m,this.U);m+=2;let d=0;this.Lb&&(d=1);f.setUint8(m,d);m+=1;f.setUint16(m,this.Hc);m+=2;f.setUint16(m,this.Na);m+=2;for(const p of this.Da)p.Ud&&(m=p.ye(f,m,c));
return m}Ei(f,m){if(this.yb.has(f))console.warn("OverrideNid passed id "+f+" which is already in use and cannot be overridden");else if(this.Wb.has(m))console.warn("OverrideNid passed nid "+m+" which is already in use and cannot be overridden");else{var c=new w(this,f,m);this.yb.set(f,c);this.Wb.add(m);this.Da.push(c);this.Lb=!0}}pe(f){(f=this.yb.get(f))&&this.oe(f)}qe(f){(f=this.Gc.get(f))&&this.oe(f)}Fb(){return{hasOverriddenNids:this.Lb,netValues:this.ya.map(f=>f.Fb()),netInstances:this.Da.map(f=>
f.Fb())}}fi(){return{roId:this.Pc,sid:this.Qc,netValues:this.ya.map(f=>f.Fb())}}}self.Mf=e;self.Fh=l;self.Hh=n}"use strict";
{const h=self.Fh,a=self.Mf,b=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection;function e(n){if(n)try{n.close()}catch(f){}}const l=[];class w{constructor(n,f,m){this.b=n;this.I=f;this.U=0;this.ga=m;this.ub=this.K=null;this.vc=!1;this.vb=null;this.xc=!1;this.wb=null;this.bf=this.Sc=this.qc=this.Kb=this.yc=!1;this.Ad=this.Eg=this.lf=0;this.Sg=[];this.Pg=this.Og=0;this.xa=[];this.N=this.C=this.Ea=null;this.Mg=0;this.Ue=!1;this.nf=1;this.Gd=
[];this.Vg=this.Hd=0;this.b.hj(this)}sb(n){this.U=n}j(){return this===this.b.R}bd(){return this===this.b.P}fl(){this.Og=performance.now()}gl(n){this.Pg=n}jd(n,f){n.binaryType="arraybuffer";n.onopen=()=>{"o"===f?this.vc=!0:"r"===f?this.xc=!0:"u"===f&&(this.yc=!0);this.Kj()};n.onmessage=m=>{this.ek(f,m)};n.onerror=m=>{console.error("Peer '"+this.I+"' datachannel '"+f+"' error: ",m);this.b.Ha(this,m);this.b.j()&&!this.j()&&this.T("network error")};n.onclose=()=>{this.T("disconnect")}}Of(){if(!this.bd()){var n=
this.b.j();this.qc=this.Kb=this.yc=this.xc=this.vc=!1;this.Eg=performance.now();this.K=new b({iceServers:this.b.ff});this.K.onicecandidate=m=>{m.candidate&&this.b.Ga({message:"icecandidate",toclientid:this.I,icecandidate:m.candidate})};this.K.onsignalingstatechange=()=>{this.K&&"closed"===this.K.signalingState&&this.T("disconnect")};this.K.oniceconnectionstatechange=()=>{this.K&&("failed"!==this.K.iceConnectionState&&"closed"!==this.K.iceConnectionState||this.T("disconnect"))};this.K.onconnectionstatechange=
()=>{if(this.K){var m=this.K.connectionState;"failed"!==m&&"closed"!==m||this.T("disconnect")}};var f=`c2mp_${this.b.Th()}_${this.b.Uh()}_${this.b.Vh()}`;n?(this.U=this.b.If(),this.ub=this.K.createDataChannel("o",{ordered:!0,protocol:f}),this.jd(this.ub,"o"),this.vb=this.K.createDataChannel("r",{ordered:!1,protocol:f}),this.jd(this.vb,"r"),this.wb=this.K.createDataChannel("u",{ordered:!1,maxRetransmits:0,protocol:f}),this.jd(this.wb,"u"),this.K.createOffer().then(m=>{this.K.setLocalDescription(m);
this.b.Ga({message:"offer",toclientid:this.I,offer:m})}).catch(m=>{console.error("Host error creating offer for peer '"+this.I+"': ",m);this.b.Ha(this,"could not create offer for peer")})):this.K.ondatachannel=m=>{if(m.channel.protocol!==f)console.error("Unexpected datachannel protocol '"+m.channel.protocol+"', should be '"+f+"'"),this.b.Ha(this,"unexpected datachannel protocol '"+m.channel.protocol+"', should be '"+f+"'");else{var c=m.channel.label;"o"===c?this.ub=m.channel:"r"===c?this.vb=m.channel:
"u"===c?this.wb=m.channel:(console.error("Unknown datachannel label: "+m.channel.label),this.b.Ha(this,"unknown datachannel label '"+m.channel.label+"'"));this.jd(m.channel,c)}}}}async gj(n){if(this.K)try{await this.K.addIceCandidate(n)}catch(f){console.warn("[Multiplayer] Error adding ICE candidate: ",f)}}hi(){return!!this.K}Kj(){!this.Kb&&this.xc&&this.yc&&this.vc&&(this.ik(),this.Kb=!0,this.qc=!1)}ik(){this.lf=performance.now();if(this.b.j()){this.b.$b("o",JSON.stringify({c:"j",i:this.I,n:this.U,
a:this.ga}),this);this.fb("o",JSON.stringify({c:"hi",hn:this.b.R.U,n:this.U,d:this.b.Ba,u:this.b.Jc,objs:this.b.ei(),cvs:this.b.Sh()}));for(const n of this.b.Ja)!n.j()&&n!==this&&n.ke()&&this.fb("o",JSON.stringify({c:"j",i:n.I,n:n.U,a:n.ga}))}else this.bf=!0,this.j()&&this.se(performance.now(),!0);this.b.rg(this)}Jj(n){!this.qc&&this.Kb&&(this.Ie(n),this.qc=!0,this.Kb=!1)}Ie(n){this.b.j()&&!this.bd()&&this.b.$b("o",JSON.stringify({c:"l",i:this.I,a:this.ga,r:n}),this);this.bd()||this.b.qg(this,n)}ke(){return this.Kb&&
!this.qc}fb(n,f){this.b.cj();var m=0;f.length?m=f.length:f.byteLength&&(m=f.byteLength);this.b.aj(m);m=this.b.zf;const c=this.b.yf,d=this.b.Af;if(!(0<m&&"u"===n&&Math.random()<m))if(0===c&&0===d)this.jg(n,f);else{let p=1;"u"!==n&&Math.random()<m&&(p=3);setTimeout(()=>this.jg(n,f),c*p+Math.random()*d*p)}}jg(n,f){try{"o"===n?this.vc&&this.ub&&this.ub.send(f):"r"===n?this.xc&&this.vb&&this.vb.send(f):"u"===n&&this.yc&&this.wb&&this.wb.send(f)}catch(m){this.Sc||(this.b.j()?"o"===n||"r"===n?("string"===
typeof f?(console.error("Error sending "+f.length+"-char string on '"+n+"' to '"+this.ga+"', host kicking: ",m),console.log("String that failed to send from previous error was: "+f)):console.error("Error sending "+(f.length||f.byteLength)+"-byte binary on '"+n+"' to '"+this.ga+"', host kicking: ",m),this.T("network error")):(this.Ad++,10<=this.Ad&&("string"===typeof f?(console.error("Too many errors ("+this.Ad+") sending data on '"+n+"' to '"+this.ga+"', kicking; last error was for sending "+f.length+
"-char string: ",m),console.log("String that failed to send from previous error was: "+f)):console.error("Too many errors ("+this.Ad+") sending data on '"+n+"' to '"+this.ga+"', kicking; last error was for sending "+(f.length||f.byteLength)+"-byte binary: ",m),this.T("network error"))):console.error("Error sending data on '"+n+"': ",m))}}se(n,f){this.Sc||(!f&&!this.ke()&&this.K&&25E3<n-this.Eg?(console.warn("Timed out '"+this.ga+"', could not establish connection after 25sec"),this.T("timeout")):
!f&&this.ke()&&2E4<n-this.lf?(console.warn("Timed out '"+this.ga+"', not heard from for 20sec"),this.T("timeout")):(this.Mg=n,this.Ue=!0,this.nf++,this.fb("u","ping:"+this.nf)))}Ii(n){n="pong:"+n.substr(5);this.b.j()&&(n=n+"/"+Math.round(performance.now()).toString());this.fb("u",n)}mk(n){if(this.Ue){var f=n.indexOf(":");if(-1<f){if(parseFloat(n.substr(f+1))===this.nf){f=performance.now();this.Ue=!1;var m=(f-this.Mg)/2;this.Gd.push(m);10<this.Gd.length&&this.Gd.shift();l.push(...this.Gd);l.sort((t,
x)=>t-x);this.Vg=l[l.length-1]-l[0];var c=0,d=l.length;4<=l.length&&6>=l.length?(++c,--d):6<l.length&&(c+=2,d-=2);var p=0;for(let t=c;t<d;++t)p+=l[t];this.Hd=p/(d-c);l.length=0;this.b.j()||(c=n.indexOf("/"),-1<c?(n=parseFloat(n.substr(c+1)),isFinite(n)?this.b.oh(n,f,m,this.Hd):console.warn("Invalid host time from pong response")):console.warn("Cannot parse off host time from pong response"))}}else console.warn("Cannot parse off ping ID from pong")}}ek(n,f){const m=this.b.zf,c=this.b.yf,d=this.b.Af;
if(!(0<m&&"u"===n&&Math.random()<m))if(0===c&&0===d)this.ig(n,f);else{let p=1;"u"!==n&&Math.random()<m&&(p=3);setTimeout(()=>this.ig(n,f),c*p+Math.random()*d*p)}}ig(n,f){if(!this.Sc){this.lf=performance.now();this.b.bj();var m=0;f.data.length?m=f.data.length:f.data.byteLength&&(m=f.data.byteLength);this.b.$i(m);if("string"===typeof f.data){if(!(""===f.data.trim()||4>f.data.length))if(n=f.data.substr(0,4),"ping"===n)this.Ii(f.data);else if("pong"===n)this.mk(f.data);else{try{var c=JSON.parse(f.data)}catch(d){this.b.Ha(this,
d);this.b.j()?(console.error("Error parsing message as JSON for peer '"+this.I+"', host kicking: ",d),this.T("data error")):console.error("Error parsing message as JSON for peer '"+this.I+"': ",d);console.log("String that failed to parse from previous error: "+f.data);return}if(c)try{c.c&&"m"!==c.c?this.Pj(c):this.b.jk(this,c)}catch(d){this.b.Ha(this,d),this.b.j()?(console.error("Error handling message for peer '"+this.I+"', host kicking: ",d),this.T("data error")):console.error("Error handling message for peer '"+
this.I+"': ",d)}}}else{!this.bf&&this.b.j()&&"u"===n&&(this.bf=!0,this.b.Ui(this.I));try{this.Oj(f.data)}catch(d){this.b.Ha(this,d),this.b.j()?(console.error("Error handling binary update for peer '"+this.I+"', host kicking: ",d),this.T("data error")):console.error("Error handling binary update for peer '"+this.I+"': ",d)}}}}Pj(n){switch(n.c){case "disconnect":n.k&&z(this.b,"peer-kicked");var f=!this.b.j()&&!this.j();this.T(n.r);f&&this.b.ve();break;case "hi":this.b.j()||(this.b.R.sb(n.hn),this.b.P.sb(n.n),
this.b.Li(n.d),this.b.Qi(n.u),this.b.vi(n.objs),this.b.ti(n.cvs));break;case "j":this.b.j()||(f=new w(this.b,n.i,n.a),f.sb(n.n),this.b.rg(f));break;case "l":!this.b.j()&&(f=this.b.Zc(n.i))&&(f.bd()||this.b.qg(f,n.r),f.T(n.r));break;default:console.error("Unknown control message from peer '"+this.I+"': "+n.c),this.b.Ha(this,"unknown control message '"+n.c+"'")}}Oj(n){this.b.j()?this.ak(n):this.kk(n)}ak(n){n=new DataView(n);let f=0;var m=n.getUint32(f);f+=4;if(1664249200!==m)console.warn("Rejected packet with incorrect magic number (received '"+
m+"', expected '1664249200'");else if(m=n.getFloat64(f),f+=8,m+=this.Hd,!(3E3<=Math.abs(m-performance.now()))){n.getUint8(f);f+=1;var c=n.getUint8(f);f+=1;var d=[],p=this.b.Ia;for(let x=0;x<c;++x)if(x>=p.length)d.push(0);else{var t=p[x];switch(t.kb){case 0:t=n.getFloat64(f);f+=8;break;case 1:t=n.getFloat32(f);f+=4;break;case 2:t=t.dd(n.getInt16(f));f+=2;break;case 3:t=t.dd(n.getUint8(f));f+=1;break;default:t=n.getFloat32(f),f+=4}d.push(t)}this.fj(m,d)}}fj(n,f){for(let m=0,c=this.xa.length;m<c;++m){const d=
this.xa[m];if(d.timestamp===n)return;if(d.timestamp>n){this.xa.splice(m,0,new h(n,f));return}}this.xa.push(new h(n,f))}fa(n){if(0!==this.xa.length){for(;2<this.xa.length&&this.xa[0]!==this.Ea&&this.xa[0]!==this.C&&this.xa[0]!==this.N;)this.xa.shift();if(!(this.N&&this.N.timestamp>n&&this.C&&this.C.timestamp<n)){this.N=null;for(let f=0,m=this.xa.length;f<m;++f){const c=this.xa[f];if(c.timestamp<=n){if(!this.C||c.timestamp>this.C.timestamp)this.Ea=this.C,this.C=c}else{this.N=c;break}}}}}kk(n){n=new DataView(n);
let f=0;var m=n.getUint32(f);f+=4;1664249200!==m?console.warn("Rejected packet with incorrect magic number (received '"+m+"', expected '1664249200'"):(m=n.getUint32(f),f+=4,0===m?this.Ej(n,f):1===m?this.Dj(n,f):console.warn("Ignoring packet with incorrect flags (received "+m+", expected 0 or 1"))}Ej(n,f){const m=n.getFloat64(f);f+=8;const c=n.getUint16(f);f+=2;for(let x=0;x<c;++x){var d=n.getUint16(f);f+=2;var p=n.getUint8(f);f+=1;let B=null,F=0;const G=this.b.Uf(d);G?(B=G.ya,F=B.length,1===p&&G.dl()):
console.warn("Don't know which object corresponds to NID "+d);d=n.getUint16(f);f+=2;p=n.getUint16(f);f+=2;for(let I=0;I<d;++I){const k=n.getUint16(f);f+=2;if(G){const q=[];let u=f;for(let g=0;g<F;++g){var t=B[g];switch(t.kb){case 0:t=n.getFloat64(u);u+=8;break;case 1:t=n.getFloat32(u);u+=4;break;case 2:t=t.dd(n.getInt16(u));u+=2;break;case 3:t=t.dd(n.getUint8(u));u+=1;break;default:t=n.getFloat32(u),u+=4}q.push(t)}G.ae(m,k,q)}f+=p}}}Dj(n,f){const m=n.getFloat64(f);f+=8;const c=n.getUint16(f);f+=2;
for(let p=0;p<c;++p){var d=n.getUint16(f);f+=2;const t=this.b.Uf(d);t||console.warn("Don't know which object corresponds to NID "+d);d=n.getUint16(f);f+=2;for(let x=0;x<d;++x){const B=n.getUint16(f);f+=2;t&&!t.Lb&&(this.b.bk(t,B,m),t.qe(B))}}}T(n,f){if(!this.Sc){this.Sc=!0;this.Jj(n);this.fb("o",JSON.stringify({c:"disconnect",r:n,k:!!f}));var m=this.ub,c=this.vb,d=this.wb,p=this.K;setTimeout(()=>{e(m);e(c);e(d);e(p)},0);this.K=this.wb=this.vb=this.ub=null;this.yc=this.xc=this.vc=!1;this.b.Sk(this)}}Yh(n){n=
n.sc;if(!this.N&&!this.C)return 0;if(this.N&&!this.C){var f=this.N.data;return 0>n||n>=f.length?0:f[n]}var m=this.b.$c();let c,d;if(!this.N&&this.C){if(this.Ea){var p=this.Ea.timestamp;f=this.Ea.data[n];c=this.C.timestamp;d=this.C.data[n];m>this.C.timestamp+250&&(m=this.C.timestamp+250);p=p===c?0:(m-p)/(c-p);return a.ad(this.b.Ia[n].eb(),f,d,p,!0)}f=this.C.data;return 0>n||n>=f.length?0:f[n]}p=this.C.timestamp;f=this.C.data[n];c=this.N.timestamp;d=this.N.data[n];p=p===c?0:(m-p)/(c-p);return a.ad(this.b.Ia[n].eb(),
f,d,p,!1)}}self.Gh=w}"use strict";
{const h=self.Mf,a=self.Gh,b=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection,e=window.RTCSessionDescription||window.webkitRTCSessionDescription||window.mozRTCSessionDescription||window.msRTCSessionDescription,l=window.RTCIceCandidate||window.webkitRTCIceCandidate||window.mozRTCIceCandidate||window.msRTCIceCandidate,w=window.RTCDataChannel||window.webkitRTCDataChannel||window.mozRTCDataChannel||window.msRTCDataChannel,n=[{urls:"stun:stun.l.google.com:19302"}];
let f=!1;const m=[];self.ra.Fa(class extends self.Sa{constructor(c){super(c,"multiplayer");this.ff=[];this.V=null;this.ua=this.Oa=!1;this.Gl={lh:0,version:0,name:"",ih:"",hh:""};this.ma=this.$e=this.Ze=this.tf=this.uf="";this.Ja=[];this.Za=new Map;this.Pb=0;this.Vd=new Set;this.R=this.P=null;this.Ba=80;this.Jc=this.ef=30;this.Rg=0;this.Cb={Vc:0,kh:0,Ff:0,jh:0,Zd:0,gh:0,Df:0,fh:0,Yd:0};this.vd=new ArrayBuffer(262144);this.Xe=new DataView(this.vd);this.Aa=[];this.Dl=1;this.Mc=new Map;this.Nc=new Map;
this.zf=this.Af=this.yf=0;this.zb=[];this.ea=this.Pa=0;this.na=this.ab=this.Ba;this.Ia=[];this.ud=new Map;this.xf=!1;this.Ge(n);setInterval(()=>this.tj(),2E3);window.addEventListener("unload",()=>this.dc("quit"));L(this,"get-supported",()=>this.Yj());L(this,"add-ice-servers",d=>this.Ge(d.list));L(this,"simulate-latency",d=>this.Ni(d.latency,d.pdv,d.loss));L(this,"set-bandwidth-profile",d=>this.Ki(d.updateRate,d.delay));L(this,"tick",d=>this.fa(d));L(this,"alert",d=>this.qh(d));L(this,"signalling-connect",
d=>this.Vi(d.url));L(this,"signalling-disconnect",()=>this.eg());L(this,"signalling-login",d=>this.Xi(d.alias));L(this,"signalling-join-room",d=>this.Wi(d.game,d.instance,d.room,d.maxClients));L(this,"signalling-auto-join-room",d=>this.Ti(d.game,d.instance,d.room,d.maxClients,d.lock));L(this,"signalling-leave-room",()=>this.ve());L(this,"signalling-list-game-instances",d=>this.Yi(d.game));L(this,"signalling-list-rooms",d=>this.Zi(d.game,d.instance,d.which));L(this,"disconnect-room",()=>this.Sf(!0));
L(this,"peer-send-message",d=>this.zi(d));L(this,"host-broadcast",d=>this.xi(d));L(this,"kick-peer",d=>this.yi(d));L(this,"sync-object",d=>this.Di(d));L(this,"sync-inst-var",d=>this.Ci(d));L(this,"associate-object",d=>this.wi(d));L(this,"remove-object-id",d=>this.pe(d.uid));L(this,"remove-net-insts",d=>this.Ai(d));L(this,"remove-object-nid",d=>this.Bi(d));L(this,"set-client-state",d=>this.ag(d.tag,d.value));L(this,"add-client-input-value",d=>this.mh(d.tag,d.precision,d.interp))}zj(c){return c?"string"===
typeof c?c:"string"===typeof c.message?c.message:"string"===typeof c.details?c.details:"string"===typeof c.data?c.data:"string"===typeof c.type?c.type:"unknown error":"unknown error"}je(){return this.Oa&&this.ua}bc(){return this.je()&&this.ma}j(){return this.bc()&&this.P&&this.R===this.P}Th(){return this.je()?this.Ze:""}Uh(){return this.je()?this.$e:""}Vh(){return this.bc()?this.ma:""}Ni(c,d,p){this.yf=Math.max(c,0);this.Af=Math.max(d,0);this.zf=Math.max(p,0)}Yj(){return{isSupported:!(!b||!w)}}Vi(c){if(!this.V&&
!this.Oa){try{this.V=new WebSocket(c,"c2multiplayer")}catch(d){this.V=null;this.rb(d);return}this.V.onopen=()=>{-1===this.V.protocol.indexOf("c2multiplayer")?(this.rb("server does not support 'c2multiplayer' protocol"),this.V.close(1002,"'c2multiplayer' protocol required"),this.V=null,this.Oa=!1):this.Oa=!0};this.V.onclose=()=>{this.vk();this.ua=this.Oa=!1;this.V=null};this.V.onerror=d=>{console.error("Signalling server error: ",d);this.rb(d)};this.V.onmessage=d=>{this.wk(d)}}}eg(){this.V&&this.Oa&&
(this.V.close(),this.V=null,this.Oa=!1)}wk(c){let d;try{d=JSON.parse(c.data)}catch(p){this.rb(p);return}switch(d.message){case "welcome":this.Ik(d);break;case "login-ok":this.Dk(d);break;case "join-ok":this.Ak(d);break;case "leave-ok":this.Ck();break;case "kicked":this.Bk();break;case "peer-joined":this.Fk(d);break;case "peer-quit":this.Gk(d);break;case "icecandidate":this.yk(d);break;case "offer":this.Ek(d);break;case "answer":this.xk(d);break;case "instance-list":this.zk(d);break;case "room-list":this.Hk(d);
break;case "error":this.rb(d.details);break;default:this.rb("received unknown signalling message")}}gi(c){for(const d of this.ff)if(d.urls===c.urls)return!0;return!1}Ge(c){if(c)for(let d of c)"string"===typeof d&&(d={urls:d}),this.gi(d)||(d.hasOwnProperty("url")||(d.url=d.urls),this.ff.push(d))}rb(c){z(this,"signalling-error",{message:this.zj(c)})}vk(){z(this,"signalling-close")}Ik(c){if(1>c.protocolrev||1<c.protocolrev)this.rb("signalling server protocol revision not supported"),this.eg();else{this.uf=
c.clientid;var d=this.Gl;d.lh=c.protocolrev;d.version=c.version;d.name=c.name;d.ih=c.operator;d.hh=c.motd;this.Ge(c.ice_servers);z(this,"signalling-welcome",{myid:this.uf,sigservinfo:{protocolrev:d.lh,version:d.version,name:d.name,operator:d.ih,motd:d.hh}})}}Dk(c){this.tf=c.alias;this.ua=!0;z(this,"signalling-login-ok",{myalias:this.tf})}ci(){return this.Dl++}If(){if(this.j()){do this.Pb++,65535<this.Pb&&(this.Pb=0);while(this.Vd.has(this.Pb));var c=this.Pb;this.Vd.add(c);return c}}Qh(c){this.j()&&
this.Vd.delete(c)}Ak(c){this.dc("disconnect");this.Ze=c.game;this.$e=c.instance;this.ma=c.room;this.P=new a(this,this.uf,this.tf);c.host?(this.R=this.P,this.Pb=0,this.Vd.clear(),this.R.sb(this.If())):(this.ea=this.Pa=this.zb.length=0,this.Ba=80,this.Jc=this.ef=30,this.na=this.ab=this.Ba,this.R=new a(this,c.hostid,c.hostalias),this.R.Of());z(this,"signalling-join-ok",{isHost:!!c.host,hostId:this.R.I,hostAlias:this.R.ga,game:this.Ze,gameInstance:this.$e,room:this.ma})}Ck(){this.ma="";z(this,"signalling-leave-ok")}Bk(){this.Sf();
this.ma="";z(this,"signalling-kicked")}Fk(c){if(this.ua&&this.ma&&this.j()){var d=this.Za.get(c.peerid);d&&d.T("rejoin");(new a(this,c.peerid,c.peeralias)).Of()}}Gk(c){if(this.ua&&this.ma&&this.j()){var d=this.Za.get(c.id);d&&d.T(c.reason)}}yk(c){if(this.ua&&this.ma){var d=this.Za.get(c.from);d&&d.gj(new l(c.icecandidate))}}Ek(c){if(this.ua&&this.ma&&!this.j()&&this.P&&this.R&&this.R.hi()&&c.from===this.R.I){var d=this.R.K;d.setRemoteDescription(new e(c.offer)).then(()=>{d.createAnswer().then(p=>
{d.setLocalDescription(p);this.Ga({message:"answer",toclientid:this.R.I,answer:p})}).catch(p=>{console.error("Peer error creating answer: ",p);this.Ha(this.P,"could not create answer to host offer")})}).catch(p=>{console.error("Peer error setting remote description: ",p);this.Ha(this.P,"could not set remote description")})}}xk(c){if(this.ua&&this.ma&&this.j()){var d=this.Za.get(c.from);d&&d.K.setRemoteDescription(new e(c.answer)).catch(p=>{console.error("Host error setting remote description: ",p)})}}zk(c){z(this,
"signalling-instance-list",{list:c.list})}Hk(c){z(this,"signalling-room-list",{list:c.list})}Ga(c){this.V&&this.Oa&&this.V.send(JSON.stringify(c))}Xi(c){this.ua||this.Ga({message:"login",protocolrev:1,alias:c})}Wi(c,d,p,t){this.ua&&!this.ma&&this.Ga({message:"join",game:c,instance:d,room:p,max_clients:t})}Ti(c,d,p,t,x){this.ua&&!this.ma&&this.Ga({message:"auto-join",game:c,instance:d,room:p,max_clients:t,lock_when_full:x})}ve(){this.ua&&this.Ga({message:"leave"})}Ui(c){this.ua&&this.j()&&this.Ga({message:"confirm-peer",
id:c})}Yi(c){this.V&&this.Oa&&this.Ga({message:"list-instances",game:c})}Zi(c,d,p){this.V&&this.Oa&&this.Ga({message:"list-rooms",game:c,instance:d,which:p})}Sf(c){this.ea=this.Pa=this.zb.length=0;this.dc("disconnect");for(const d of this.Aa)d.Kh();c&&this.ve()}hj(c){this.Ja.push(c);this.Za.set(c.I,c);z(this,"add-peer",{id:c.I,alias:c.ga})}Sk(c){z(this,"remove-peer",{id:c.I});this.j()&&this.Qh(c.U);const d=this.Ja.indexOf(c);-1<d&&this.Ja.splice(d,1);this.Za.delete(c.I);this.R===c&&(this.R=null,this.dc("host quit"));
this.P===c&&(this.P=null,this.ma="",this.dc("disconnect"))}dc(c){if(!f){for(f=!0;this.Ja.length;)this.Ja[0].T(c);f=!1}}Zc(c){return this.Za.get(c)||null}Rh(c){return(c=this.Za.get(c))?c.ga:""}xi(c){const d=c.fromId,p=c.tag,t=c.message;c=c.mode;const x=this.Zc(d);this.$b(c,JSON.stringify({c:"m",t:p,f:d,m:t}),x)}$b(c,d,p){if(this.j()){var t=this.Ja.slice(0);for(const x of t)x&&x!==this.P&&x!==p&&x.fb(c,d)}}tj(){const c=performance.now();if(this.j()){m.push(...this.Ja);for(const d of m)d&&d!==this.P&&
d.se(c,!1);m.length=0}else this.R&&this.R.se(c,!1)}ph(c){this.Aa.push(c);this.Nc.set(c.Pc,c);this.Mc.set(c.U,c)}ei(){const c={};for(const [d,p]of this.Mc.entries())c[p.Qc]={nid:d,nvs:p.bi()};return c}vi(c){this.Mc.clear();for(const d of this.Aa)if(c.hasOwnProperty(d.Qc.toString())){const p=c[d.Qc.toString()];d.sb(p.nid);this.Mc.set(p.nid,d);d.Oi(p.nvs)}else console.warn("Could not map object SID '"+d.Qc+"' - host did not send NID for it"),d.sb(-1)}Uf(c){return this.Mc.get(c)||null}fa(c){if(!this.bc())return null;
c=c.dt;const d=performance.now();d-this.Rg>=1E3/(this.j()?this.ef:this.Jc)-5&&(this.Ji(d),this.Rg=d);const p=this.Cb;1E3<=d-p.Vc&&(p.kh=p.Ff,p.jh=p.Zd,p.gh=p.Df,p.fh=p.Yd,p.Ff=0,p.Zd=0,p.Df=0,p.Yd=0,p.Vc+=1E3,500<d-p.Vc&&(p.Vc=d),z(this,"stats",{stats:{outboundPerSec:p.kh,outboundBandwidthPerSec:p.jh,inboundPerSec:p.gh,inboundBandwidthPerSec:p.fh}}));this.j()||(this.ea<this.Pa?(this.ea+=10*c,this.ea>this.Pa&&(this.ea=this.Pa)):this.ea>this.Pa&&(this.ea-=10*c,this.ea<this.Pa&&(this.ea=this.Pa)),this.na<
this.ab?(this.na+=30*c,this.na>this.ab&&(this.na=this.ab)):this.na>this.ab&&(this.na-=30*c,this.na<this.ab&&(this.na=this.ab)));c=this.$c();for(const t of this.Ja)t.fa(c);for(const t of this.Aa)t.fa();return{simulationTime:this.$c(),hostInputArrivalTime:this.Xh(),clientDelay:this.Ba,peerData:this.Bj(),roData:this.Cj(),isReadyForInput:this.Wf()}}Bj(){const c={};for(const d of this.Ja){const p={};for(const t of this.Ia)p[t.aa]=d.Yh(t);c[d.I]={nid:d.U,latency:d.Hd,pdv:d.Vg,clientState:p}}return c}Cj(){const c=
{};for(const d of this.Aa)c[d.Pc]=d.Fb();return c}async Ji(c){this.j()?(await this.Zk(c),this.Yk(c)):await this.Xk(c)}async Mj(){const c=await C(this,"before-client-update");for(const d of c.clientStateUpdates)this.ag(d.tag,d.value)}async Xk(c){this.Wf()&&await this.Mj();if(this.P&&this.xf){var d=this.Xe,p=0,t=this.Ia,x=this.P.Sg,B=c-this.P.Og,F=c-this.P.Pg;if(100>B||(1E3>B?95<=F:495<=F)){d.setUint32(p,1664249200);p+=4;d.setFloat64(p,c+this.ea);p+=8;d.setUint8(p,0);p+=1;d.setUint8(p,t.length);p+=
1;for(let G=0,I=t.length;G<I;++G)B=t[G],F=0,G<x.length&&(F=B.Nf(x[G])),p=B.fg(d,p,F);this.P.gl(c);this.R.fb("u",new Uint8Array(this.vd.slice(0,p)))}}}async Zk(c){const d=this.Xe;let p=0,t=0;const x=await C(this,"get-object-info",{ros:this.Aa.map(B=>B.fi())});for(const B of this.Aa){const F=B.Pc;x.hasOwnProperty(F)&&(B.xe(x[F],c),0<B.Hc&&t++)}if(0!==t){d.setUint32(p,1664249200);p+=4;d.setUint32(p,0);p+=4;d.setFloat64(p,c);p+=8;d.setUint16(p,t);p+=2;for(const B of this.Aa)0<B.Hc&&(p=B.ye(d,p,c));this.$b("u",
new Uint8Array(this.vd.slice(0,p)),null)}}Yk(c){const d=this.Xe;let p=0,t=0;for(const x of this.Aa)x.wd.length&&t++;if(0!==t){d.setUint32(p,1664249200);p+=4;d.setUint32(p,1);p+=4;d.setFloat64(p,c);p+=8;d.setUint16(p,t);p+=2;for(const x of this.Aa)if(c=x.wd,c.length){d.setUint16(p,x.U);p+=2;d.setUint16(p,c.length);p+=2;for(const B of c)d.setUint16(p,B),p+=2;c.length=0}this.$b("r",new Uint8Array(this.vd.slice(0,p)),null)}}oh(c,d,p,t){if(!this.j()){this.ab=t+this.Ba;c=c+p-d;0===this.zb.length&&(this.ea=
c,this.na=this.ab);this.zb.push(c);30<this.zb.length&&this.zb.shift();m.push(...this.zb);m.sort((x,B)=>x-B);c=0;d=m.length;4<=m.length&&6>=m.length?(++c,--d):6<m.length&&19>=m.length?(c+=2,d-=2):19<m.length&&(c+=5,d-=5);p=0;for(t=c;t<d;++t)p+=m[t];this.Pa=p/(d-c);m.length=0}}$c(){return this.j()?performance.now()-this.Ba:performance.now()+this.ea-this.na}Xh(){return this.j()?performance.now():performance.now()+this.ea+this.na}ag(c,d){if(!this.j()&&this.P&&this.xf&&(c=this.ud.get(c))){c=c.sc;var p=
this.P.Sg;p.length<c+1&&(p.length=c+1);p[c]!==d&&(p[c]=d,this.P.fl())}}mh(c,d,p){d=new h(this.Ia.length,p,d,c,null);this.ud.set(c,d);this.Ia.push(d)}Sh(){const c=[];for(const d of this.Ia)c.push({tag:d.aa,precision:d.kb,interp:d.eb()});return c}ti(c){this.ud.clear();this.Ia.length=0;for(let p=0,t=c.length;p<t;++p){var d=c[p];d=new h(p,d.interp,d.precision,d.tag,null);this.ud.set(d.aa,d);this.Ia.push(d)}this.xf=!0}pe(c){for(const d of this.Aa)d.pe(c)}Wf(){return this.bc()?this.j()?!0:0!==this.Pa:!1}Ki(c,
d){this.bc()||(this.Jc=this.ef=c,this.Ba=d)}rg(c){z(this,"peer-open",{id:c.I,alias:c.ga})}zi(c){const d=c.tag,p=c.message,t=c.mode;(c=this.Zc(c.id))&&c.fb(t,JSON.stringify({c:"m",t:d,m:p}))}qg(c,d){z(this,"peer-close",{id:c.I,alias:c.ga,reason:d||"unknown"})}Ha(c,d){console.error(`[Multiplayer] Peer '${c.ga}' (${c.I}) error: `,d)}jk(c,d){c=d.f||c.I;z(this,"peer-message",{tag:d.t,fromId:c,fromAlias:this.Rh(c),content:d.m})}bk(c,d,p){z(this,"instance-destroyed",{roId:c.Pc,nid:d,timestamp:p})}yi(c){if(this.j()){var d=
c.reason;(c=this.Zc(c.id))&&c.T(d,!0)}}cj(){this.Cb.Ff++}aj(c){this.Cb.Zd+=c}bj(){this.Cb.Df++}$i(c){this.Cb.Yd+=c}Li(c){this.Ba=c}Qi(c){this.Jc=c}Di(c){const d=c.data,p=c.precision,t=c.bandwidth;for(const x of c.objectClasses)c=new self.Hh(this,x.roId,x.sid,t),1===d?(c.cb(1,p,"x"),c.cb(1,p,"y")):2===d?c.cb(2,p,"a"):3===d&&(c.cb(1,p,"x"),c.cb(1,p,"y"),c.cb(2,p,"a"))}qh(c){alert(c.message)}Ci(c){const d=c.precision,p=c.interp,t=c.cvt;for(const x of c.syncData)this.Nc.get(x.roId).cb(p,d,"iv",x.varIndex,
t)}wi(c){var d=c.peerId;const p=c.instUid;c=this.Nc.get(c.roId);d=this.Za.get(d);c&&d&&this.j()&&c.Ei(p,d.U)}Ai(c){for(const [d,p]of Object.entries(c))if(c=this.Nc.get(parseInt(d,10)))for(const t of p)c.qe(t)}Bi(c){const d=c.nid;(c=this.Nc.get(c.roId))&&c.qe(d)}})}"use strict";
{function h(b){b.stopPropagation()}function a(b){13!==b.which&&27!==b.which&&b.stopPropagation()}self.ra.Fa(class extends self.Qf{constructor(b){super(b,"text-input");R(this,"scroll-to-bottom",e=>this.tk(e))}ce(b,e){let l;const w=e.type;"textarea"===w?(l=document.createElement("textarea"),l.style.resize="none"):(l=document.createElement("input"),l.type=w);l.style.position="absolute";l.autocomplete="off";l.addEventListener("touchstart",h);l.addEventListener("touchmove",h);l.addEventListener("touchend",
h);l.addEventListener("mousedown",h);l.addEventListener("mouseup",h);l.addEventListener("keydown",a);l.addEventListener("keyup",a);l.addEventListener("click",n=>{n.stopPropagation();S(this,"click",b)});l.addEventListener("dblclick",n=>{n.stopPropagation();S(this,"dblclick",b)});l.addEventListener("input",()=>Q(this,"change",b,{text:l.value}));e.id&&(l.id=e.id);this.ec(l,e);return l}ec(b,e){b.value=e.text;b.placeholder=e.placeholder;b.title=e.title;b.disabled=!e.isEnabled;b.readOnly=e.isReadOnly;b.spellcheck=
e.spellCheck;e=e.maxLength;0>e?b.removeAttribute("maxlength"):b.setAttribute("maxlength",e)}tk(b){b.scrollTop=b.scrollHeight}})}"use strict";
{function h(a){a.stopPropagation()}self.ra.Fa(class extends self.Qf{constructor(a){super(a,"progress-bar")}ce(a,b){const e=document.createElement("progress");e.style.position="absolute";e.style.userSelect="none";e.style.webkitUserSelect="none";e.addEventListener("touchstart",h);e.addEventListener("touchmove",h);e.addEventListener("touchend",h);e.addEventListener("mousedown",h);e.addEventListener("mouseup",h);e.addEventListener("click",()=>S(this,"click",a));b.id&&(e.id=b.id);this.ec(e,b);return e}ec(a,
b){a.title=b.title;const e=b.value;b=b.max;0<b&&0<=e?(a.max=b,a.value=e):(a.removeAttribute("value"),a.removeAttribute("max"))}})};
